-- ============================================================
-- QUIZ PMRR — Migração v2
-- Novidades: militares, auth, histórico, opcao_e, categoria Prova
-- ============================================================
SET NAMES utf8mb4;
SET foreign_key_checks = 0;

-- 1. Adicionar opcao_e às questões -------------------------
ALTER TABLE questoes ADD COLUMN IF NOT EXISTS opcao_e TEXT NULL AFTER opcao_d;

-- 2. Tabela de militares (usuários) -------------------------
CREATE TABLE IF NOT EXISTS militares (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    nome_completo VARCHAR(200)  NOT NULL,
    nome_guerra   VARCHAR(100)  NOT NULL,
    email         VARCHAR(150)  NOT NULL,
    matricula     VARCHAR(20)   NOT NULL,
    senha_hash    VARCHAR(255)  NOT NULL,
    status        ENUM('pendente','aprovado','rejeitado') NOT NULL DEFAULT 'pendente',
    is_admin      TINYINT(1)    NOT NULL DEFAULT 0,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at   TIMESTAMP     NULL,
    UNIQUE KEY uq_email     (email),
    UNIQUE KEY uq_matricula (matricula)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Ajustar sessões para vincular ao militar ---------------
ALTER TABLE sessoes
    ADD COLUMN IF NOT EXISTS militar_id       INT  NULL AFTER nome_usuario,
    ADD COLUMN IF NOT EXISTS tipo             ENUM('quiz','prova') NOT NULL DEFAULT 'quiz' AFTER militar_id,
    ADD COLUMN IF NOT EXISTS numero_tentativa INT  NOT NULL DEFAULT 1 AFTER tipo;

-- 4. Nova categoria: Prova ----------------------------------
INSERT IGNORE INTO categorias (nome, descricao)
VALUES ('🎯 Prova', 'Questões Revisadas — Estatuto (LC 194/2012) e CEDM/RR (Lei 963/2014)');

-- Obter o ID da categoria Prova
SET @cat_prova = (SELECT id FROM categorias WHERE nome = '🎯 Prova' LIMIT 1);

-- 5. Inserir 80 questões da Prova (opcao_a..e + nivel) ------
INSERT INTO questoes
    (categoria_id, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, opcao_e,
     resposta_correta, explicacao, referencia_legal, nivel)
VALUES
(@cat_prova,
 'Os militares estaduais da reserva remunerada, quando convocados, ficam proibidos de tratar nas organizações militares e repartições públicas civis de:',
 'Assuntos relacionados à sua própria situação funcional.',
 'Interesses de organizações ou empresas privadas de qualquer natureza.',
 'Questões previdenciárias ou de benefícios a que façam jus.',
 'Assuntos de interesse exclusivamente pessoal perante a Administração Pública.',
 'Matérias relacionadas a procedimentos disciplinares que lhes digam respeito.',
 'B',
 'O Estatuto veda ao militar da reserva remunerada convocado tratar, nas organizações militares e repartições públicas civis, de interesses de organizações ou empresas privadas de qualquer natureza.',
 'Art. 40, §1º, LC nº 194/2012',
 'medio'),

(@cat_prova,
 'A acumulação lícita do cargo de militar estadual com outro cargo de provimento efetivo é permitida:',
 'Somente para oficiais superiores, nas áreas de saúde ou educação, independentemente de horário.',
 'Apenas para militares do Quadro de Saúde, em qualquer área, desde que autorizado pelo Comandante-Geral.',
 'Para todos os militares da ativa, em qualquer área, desde que não haja prejuízo ao serviço.',
 'Somente para praças da área de saúde, vedada aos oficiais.',
 'Aos oficiais por sua formação científica e às praças por sua formação técnico-profissional, nas áreas de saúde ou educação, desde que haja compatibilidade de horários.',
 'E',
 'A redação do Estatuto permite a acumulação lícita com outro cargo efetivo nas áreas de saúde ou educação, desde que haja compatibilidade de horários.',
 'Art. 40, §2º, LC nº 194/2012',
 'medio'),

(@cat_prova,
 'O CEDM/RR estabelece preceito ético que regula a conduta do militar quanto ao uso da estrutura do Estado posta à sua disposição. Qual é esse preceito?',
 'Não abusar dos meios do Estado postos à sua disposição, nem distribuí-los em detrimento dos fins da Administração Pública, coibindo a transferência, para fins particulares, de tecnologia própria das funções militares.',
 'Atuar com eficiência e probidade, zelando pela economia e conservação dos bens públicos cuja utilização lhe for confiada.',
 'Abster-se do uso do posto, graduação ou função para obter facilidades pessoais de qualquer natureza.',
 'Não usar meio ilícito na produção de trabalho intelectual ou em avaliação profissional.',
 'Exercer a função pública com honestidade, não aceitando vantagens de qualquer espécie.',
 'A',
 'A alternativa reproduz o preceito ético que veda o abuso dos meios do Estado e a transferência de tecnologia institucional para fins particulares.',
 'Art. 20, XXVI, Lei nº 963/2014',
 'medio'),

(@cat_prova,
 'O que NÃO é computável para efeito algum no tempo de serviço do militar estadual de Roraima?',
 'O tempo passado em licença para tratar de interesse particular.',
 'O tempo de serviço prestado às Forças Armadas anteriormente ao ingresso na corporação.',
 'O tempo de afastamento por ferimento em serviço na preservação da ordem pública.',
 'O tempo de matrícula no curso de formação anteriormente à posse no cargo efetivo.',
 'O tempo de serviço prestado nas Guardas Territoriais em atividades policiais militares.',
 'A',
 'O tempo em licença para tratar de interesse particular não é computado para efeito de tempo de serviço, diferentemente de períodos legalmente computáveis ou averbações admitidas.',
 'LC nº 194/2012, regras de tempo de serviço',
 'facil'),

(@cat_prova,
 'O CEDM/RR prevê preceito ético que impõe ao militar postura irrepreensível tanto na esfera pública quanto na particular. Qual é esse preceito?',
 'Tratar de forma urbana, cordial e educada os cidadãos.',
 'Ser fiel na vida militar, cumprindo os compromissos de agente público.',
 'Manter ânimo forte e fé na missão militar, mesmo diante das dificuldades.',
 'Observar os direitos e garantias fundamentais, agindo com isenção e equidade.',
 'Proceder de maneira ilibada na vida pública e na particular.',
 'E',
 'O Código exige que o militar proceda de maneira ilibada tanto na vida pública quanto na particular, reforçando a extensão da ética militar para além do serviço.',
 'Art. 20, XXXIII, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'A passagem do militar estadual da ativa para a inatividade mediante transferência para a reserva remunerada pode ocorrer de quais formas?',
 'Apenas ex-officio, por iniciativa da corporação.',
 'Apenas a pedido, mediante requerimento do militar.',
 'Por três formas: a pedido, ex-officio e por tempo de contribuição.',
 'Por quatro formas: a pedido, ex-officio, por reforma e por licenciamento.',
 'Por duas formas: a pedido e ex-officio.',
 'E',
 'A transferência para a reserva remunerada ocorre a pedido ou ex-officio. Reforma e licenciamento são formas diversas de desligamento/inatividade, não modalidades de transferência para a reserva.',
 'LC nº 194/2012, transferência para reserva remunerada',
 'medio'),

(@cat_prova,
 'A exoneração de ofício dar-se-á quando o militar tiver tomado posse, mas não entrar em exercício no prazo estabelecido. Além dessa hipótese, quais outras situações autorizam a exoneração de ofício?',
 'Quando o militar for condenado à pena de reforma administrativa disciplinar.',
 'Quando o militar ultrapassar dois anos em licença para tratar de interesse particular.',
 'Quando o militar for enquadrado nos casos previstos no art. 131 do Estatuto.',
 'Quando não forem satisfeitas as condições do estágio probatório e quando o oficial for enquadrado nas condições previstas no §2º do art. 115-D.',
 'Quando o militar for declarado desertor ou oficialmente extraviado.',
 'D',
 'A exoneração de ofício também ocorre quando não satisfeitas as condições do estágio probatório e nas hipóteses específicas previstas para oficial no Estatuto.',
 'LC nº 194/2012, exoneração de ofício',
 'dificil'),

(@cat_prova,
 'A demissão será aplicada ao oficial em quais casos?',
 'Apenas nos casos de crime militar, julgados pelo Conselho de Justificação.',
 'Exclusivamente por improbidade administrativa e insubordinação em serviço.',
 'Somente por crime contra a Administração Pública, conforme o Código Penal Militar.',
 'Crime contra a Administração Pública, improbidade administrativa, insubordinação em serviço e demais casos previstos em lei.',
 'Apenas nos casos de condenação criminal com pena restritiva de liberdade superior a dois anos.',
 'D',
 'A demissão do oficial é medida grave prevista para hipóteses como crime contra a Administração Pública, improbidade, insubordinação e demais situações legais.',
 'LC nº 194/2012, demissão de oficial',
 'medio'),

(@cat_prova,
 'O militar estadual beneficiado por afastamento para curso de capacitação, formação, especialização ou aperfeiçoamento deve permanecer no exercício das funções após o retorno por qual período?',
 'Por um período mínimo de dois anos, independentemente da duração do afastamento.',
 'Pelo dobro do período do afastamento concedido.',
 'Por um período igual ao do afastamento concedido.',
 'Por um período de no mínimo seis meses, qualquer que seja a duração do curso.',
 'Pelo período fixado pelo Comandante-Geral no ato de concessão do afastamento.',
 'C',
 'A regra de permanência vincula o militar ao exercício das funções por período igual ao afastamento concedido, evitando que o investimento público seja perdido logo após o retorno.',
 'LC nº 194/2012, afastamento para curso',
 'medio'),

(@cat_prova,
 'Caso o militar estadual solicite exoneração ou aposentadoria antes de cumprido o período de permanência exigido após curso, qual é a consequência?',
 'Deverá ressarcir a corporação, proporcionalmente aos meses que faltam para completar o período previsto.',
 'Terá a exoneração negada até completar integralmente o período de permanência obrigatório.',
 'Ficará agregado à corporação até o cumprimento integral do período de permanência.',
 'Será licenciado ex-officio, sem direito a qualquer indenização ou remuneração.',
 'Poderá ser exonerado sem qualquer ônus, desde que comprove motivo de força maior.',
 'A',
 'Se não cumprir o período de permanência após curso custeado pelo Estado, deve ressarcir proporcionalmente o período que faltar.',
 'LC nº 194/2012, afastamento para curso',
 'medio'),

(@cat_prova,
 'Qual das seguintes hipóteses NÃO está prevista como causa de desligamento ou exclusão do serviço ativo?',
 'Transferência para a reserva remunerada.',
 'Exclusão a bem da disciplina.',
 'Suspensão disciplinar por prazo determinado.',
 'Reforma administrativa disciplinar.',
 'Perda do posto e patente.',
 'C',
 'Suspensão disciplinar é sanção temporária e não equivale a causa de desligamento ou exclusão do serviço ativo.',
 'LC nº 194/2012, desligamento/exclusão',
 'facil'),

(@cat_prova,
 'Posto e Graduação são graus hierárquicos dos Oficiais e das Praças. Segundo o CEDM/RR, qual é a diferença quanto à autoridade que os confere?',
 'O Posto é conferido pelo Comandante-Geral; a Graduação, pelo Governador.',
 'O Posto é conferido pelo Secretário de Segurança Pública; a Graduação, pelo Comandante-Geral.',
 'O Posto é conferido por ato do Governador do Estado e atestado em carta patente; a Graduação é conferida pelos Comandantes-Gerais da PM e do CBM.',
 'Tanto o Posto quanto a Graduação são conferidos pelo Governador.',
 'O Posto é conferido pela Assembleia Legislativa; a Graduação, pelo Governador.',
 'C',
 'O Posto é próprio dos oficiais e vem de ato do Governador com carta patente; a Graduação é própria das praças e é conferida pelos Comandantes-Gerais.',
 'Art. 5º, §§1º e 2º, Lei nº 963/2014',
 'medio'),

(@cat_prova,
 'O compromisso de honra previsto no CEDM/RR é prestado por todo cidadão ao ingressar nas carreiras militares estaduais. Qual é o momento e o conteúdo desse compromisso?',
 'É prestado ao término do curso de formação e consiste na afirmação da aceitação consciente das obrigações e deveres militares e na firme disposição de bem cumpri-los.',
 'É prestado no ato da posse e consiste na declaração de fidelidade exclusiva à Constituição Federal.',
 'É prestado antes do curso de formação e consiste na declaração de aptidão física e mental.',
 'É prestado a cada promoção hierárquica e consiste na renovação do juramento à corporação.',
 'É prestado ao término do estágio probatório e consiste no compromisso de permanência mínima de dez anos.',
 'A',
 'O compromisso é prestado ao término do curso de formação, com aceitação consciente das obrigações e deveres militares.',
 'Art. 22, Lei nº 963/2014',
 'medio'),

(@cat_prova,
 'O CEDM/RR veda ao militar da ativa determinadas atividades. Qual é a regra estabelecida e qual a exceção prevista?',
 'É vedado exercer qualquer atividade remunerada fora da corporação, sem exceção.',
 'É vedado exercer atividade de segurança particular e atividade comercial ou industrial, ressalvadas as permitidas pela legislação vigente.',
 'É vedado exercer atividade política, sindical ou associativa de qualquer natureza.',
 'É vedado exercer atividade comercial, sendo permitida a segurança particular em folga.',
 'É vedado exercer atividade remunerada, exceto magistério público.',
 'B',
 'O Código veda segurança particular e atividade comercial/industrial ao militar da ativa, salvo exceções previstas em legislação.',
 'Art. 21, Lei nº 963/2014',
 'medio'),

(@cat_prova,
 'Quando o militar houver realizado curso ou estágio com duração superior a seis meses por conta do Estado, qual condição permite a transferência para a reserva remunerada a pedido antes de decorridos 24 meses do término?',
 'A transferência só será concedida mediante indenização de todas as despesas decorrentes da realização do curso ou estágio.',
 'A transferência será concedida se comprovar aplicação dos conhecimentos adquiridos.',
 'A transferência será concedida por autorização do Governador, sem indenização.',
 'A transferência será vedada por prazo indeterminado.',
 'A transferência poderá ocorrer após devolução parcial, a critério do Comandante-Geral.',
 'A',
 'Quando o curso/estágio custeado pelo Estado for superior a seis meses, a transferência antes de 24 meses exige indenização das despesas.',
 'LC nº 194/2012, reserva remunerada após curso custeado',
 'dificil'),

(@cat_prova,
 'Qual obrigação dos Subtenentes e Sargentos em relação às Praças diretamente subordinadas está correta?',
 'Assegurar a observância minuciosa e ininterrupta das ordens, regras do serviço e normas operativas pelas Praças subordinadas, bem como a manutenção da coesão e da moral.',
 'Apenas avaliar o desempenho das Praças e encaminhar relatórios ao Oficial superior.',
 'Aplicar sanções disciplinares às Praças sem comunicação ao Oficial.',
 'Substituir os Oficiais no comando das Organizações Militares sempre que necessário.',
 'Apenas executar atividades operacionais sem responsabilidade sobre Praças subordinadas.',
 'A',
 'Subtenentes e Sargentos auxiliam os Oficiais e devem impor-se pelo exemplo, assegurando ordens, regras, normas, coesão e moral.',
 'Art. 13, parágrafo único, Lei nº 963/2014',
 'medio'),

(@cat_prova,
 'Como devem ser empregados os Cabos e Soldados nas corporações militares estaduais?',
 'Prioritariamente em atividades administrativas e logísticas.',
 'Em funções de assessoramento e suporte aos Oficiais.',
 'Preferencialmente em atividades de instrução e adestramento.',
 'Em missões de inteligência e investigação policial.',
 'Prioritariamente na execução das atividades operacionais, pautando-se pelo conhecimento das normas necessárias aos serviços e missões.',
 'E',
 'Cabos e Soldados são destinados prioritariamente à execução das atividades operacionais.',
 'Art. 14, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'O militar deve manter conduta idônea:',
 'Apenas durante o serviço ativo, enquanto estiver fardado.',
 'Somente nas unidades militares e em operações.',
 'Apenas durante o estágio probatório.',
 'Quer na ativa, quer na inatividade, sem prejudicar disciplina e decoro militar.',
 'Somente em eventos públicos e representação institucional.',
 'D',
 'O Estatuto exige conduta idônea tanto na ativa quanto na inatividade, preservando disciplina e decoro.',
 'Art. 39, XX, LC nº 194/2012',
 'facil'),

(@cat_prova,
 'O que são as dispensas de serviço como recompensa?',
 'Autorizações concedidas aos militares para afastamento total ou parcial do serviço, em caráter temporário.',
 'Penalidades aplicadas por infrações disciplinares.',
 'Licenças especiais concedidas a cada quinquênio.',
 'Afastamentos definitivos por incapacidade física.',
 'Suspensões cautelares durante processos disciplinares.',
 'A',
 'A dispensa de serviço é recompensa e pode ser total ou parcial, isentando o militar de trabalhos da OM ou de alguns trabalhos especificados.',
 'Art. 80, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'A Ordenação da Autoridade no CEDM/RR se faz por postos e graduações. Quais são os três critérios expressamente previstos?',
 'Tempo de serviço, mérito pessoal e avaliação de desempenho.',
 'Formação acadêmica, especialização técnica e antiguidade.',
 'Data de ingresso, região de lotação e grau de instrução.',
 'Antiguidade, avaliação de desempenho e posto ou graduação.',
 'Escalonamento hierárquico, antiguidade e precedência funcional.',
 'E',
 'O Código fala em postos e graduações conforme escalonamento hierárquico, antiguidade e precedência funcional.',
 'Art. 6º, Lei nº 963/2014',
 'medio'),

(@cat_prova,
 'Sobre o dever de manter disciplina, qual afirmação está correta?',
 'A disciplina deve ser mantida apenas no serviço ativo e em operações.',
 'A disciplina e o respeito à hierarquia devem ser mantidos permanentemente pelos militares na ativa e na inatividade.',
 'A disciplina é exigida somente nas organizações militares.',
 'A disciplina é obrigatória somente no horário de trabalho e solenidades.',
 'A disciplina é exigida apenas em missão operacional.',
 'B',
 'A disciplina e o respeito à hierarquia permanecem exigíveis na ativa e na inatividade.',
 'Art. 8º, §2º, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'Qual alternativa reflete corretamente a forma de emprego dos Cabos e Soldados?',
 'Atividades administrativas e logísticas prioritariamente.',
 'Assessoramento e suporte aos Oficiais.',
 'Instrução e adestramento preferencialmente.',
 'Inteligência e investigação policial.',
 'Execução prioritária das atividades operacionais, com conhecimento das normas dos serviços e missões.',
 'E',
 'O art. 14 repete que Cabos e Soldados devem ser empregados prioritariamente nas atividades operacionais.',
 'Art. 14, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'A nomeação do militar para cargo de provimento efetivo depende de:',
 'Aprovação apenas na primeira etapa, com aproveitamento mínimo de 60%.',
 'Prévia habilitação em todas as fases do concurso público, obedecida a ordem de classificação e o prazo de validade.',
 'Indicação do Comandante-Geral da corporação.',
 'Aprovação apenas nas etapas médica e psicológica.',
 'Autorização do Governador do Estado, independentemente da classificação.',
 'B',
 'A nomeação exige habilitação em todas as fases, respeitada a classificação e a validade do concurso.',
 'Art. 13, LC nº 194/2012',
 'facil'),

(@cat_prova,
 'A investidura no cargo da Polícia Militar ou do Corpo de Bombeiros Militar de Roraima ocorre de que forma?',
 'Por portaria do Comandante-Geral.',
 'Através da posse no respectivo cargo.',
 'Por decreto do Governador publicado no Diário Oficial.',
 'Mediante certificado de conclusão do curso.',
 'Por resolução da Assembleia Legislativa.',
 'B',
 'A investidura ocorre por meio da posse no respectivo cargo.',
 'Art. 14, LC nº 194/2012',
 'facil'),

(@cat_prova,
 'Na hipótese de liminar judicial que modifique a ordem de classificação do concurso entre o resultado e a posse, o candidato beneficiado tomará posse em:',
 'Vaga definitiva, com todos os direitos e vantagens.',
 'Cargo em comissão até decisão definitiva.',
 'Vaga suplementar criada para esse fim.',
 'Cargo temporário, sem estabilidade.',
 'Vaga reservada em natureza precária.',
 'E',
 'O candidato beneficiado por liminar toma posse em vaga reservada de natureza precária.',
 'Art. 16, LC nº 194/2012',
 'dificil'),

(@cat_prova,
 'O concurso público para ingresso na PMRR/CBMRR é composto por quantas etapas e qual é o caráter da quarta etapa?',
 'Três etapas; a terceira é classificatória.',
 'Cinco etapas; a quinta é curso de formação.',
 'Duas etapas; ambas eliminatórias.',
 'Quatro etapas; a quarta é investigação social, de caráter eliminatório.',
 'Quatro etapas; a quarta é exame de aptidão física, classificatório.',
 'D',
 'O concurso possui quatro etapas, sendo a quarta a investigação social, de caráter eliminatório.',
 'Art. 12, IV, LC nº 194/2012',
 'medio'),

(@cat_prova,
 'O militar estadual adquire estabilidade ao completar quanto tempo de efetivo exercício e cumprir qual condição?',
 '2 anos, com aprovação em curso de aperfeiçoamento.',
 '5 anos, independentemente de avaliação.',
 '3 anos de efetivo exercício e aprovação em avaliação de desempenho técnico-profissional e conduta social civil ilibada.',
 '4 anos, com conceito ótimo em todas as avaliações.',
 '3 anos exclusivamente pelo decurso do tempo.',
 'C',
 'A estabilidade exige 3 anos e aprovação em avaliação de desempenho técnico-profissional e conduta social civil ilibada.',
 'Art. 20, LC nº 194/2012',
 'medio'),

(@cat_prova,
 'O oficial adquire estabilidade em que momento e mediante qual condição?',
 'No ato da promoção ao primeiro posto, após período mínimo de seis meses como Aspirante-a-Oficial, com conceito favorável da Comissão de Avaliação e Mérito ou equivalente.',
 'No ato da matrícula no curso de formação.',
 'Ao completar 3 anos, igual a todos os militares.',
 'No ato da posse, independentemente de avaliação.',
 'Ao concluir 30 meses de estágio probatório.',
 'A',
 'O oficial adquire estabilidade na promoção ao primeiro posto, considerado o período de Aspirante-a-Oficial e conceito favorável.',
 'Art. 20, §1º, LC nº 194/2012',
 'dificil'),

(@cat_prova,
 'A camaradagem é indispensável ao convívio dos militares. Qual obrigação o Código impõe a todos os integrantes da PM e do CBM?',
 'Respeitar hierarquia e cumprir ordens sem questionamentos.',
 'Incentivar e manter a harmonia e a solidariedade entre si.',
 'Promover competições saudáveis.',
 'Reportar qualquer desvio ao superior imediato.',
 'Participar de todas as atividades sociais da corporação.',
 'B',
 'O Código impõe o dever de incentivar e manter harmonia e solidariedade entre os militares.',
 'Art. 16, parágrafo único, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'Como são definidos e conferidos o posto e a graduação no Estatuto?',
 'Posto é o grau hierárquico do Oficial, conferido por ato do Governador e confirmado pela Carta Patente; Graduação é o grau hierárquico da Praça, conferido pelo Comandante-Geral.',
 'Posto é grau da Praça; Graduação é grau do Oficial.',
 'Posto e Graduação são conferidos exclusivamente pelo Governador.',
 'Posto é conferido pelo Ministério da Defesa; Graduação pelo Governador.',
 'Posto é conferido pelo Comandante-Geral; Graduação pelo Governador.',
 'A',
 'O Estatuto define Posto para Oficiais e Graduação para Praças, com autoridades distintas para conferi-los.',
 'Art. 25, §§1º e 2º, LC nº 194/2012',
 'medio'),

(@cat_prova,
 'O compromisso de honra prestado pelo militar ao ingressar na carreira tem qual finalidade essencial?',
 'Confirmar a aptidão física e intelectual do militar.',
 'Formalizar a posse no cargo de provimento efetivo.',
 'Registrar juramento exclusivo ao Governador.',
 'Firmar a aceitação consciente das obrigações e deveres de sua função militar.',
 'Substituir o estágio probatório.',
 'D',
 'O compromisso de honra firma a aceitação consciente das obrigações e deveres da função militar.',
 'Art. 42, LC nº 194/2012',
 'facil'),

(@cat_prova,
 'Após retorno de afastamento para curso de capacitação, formação, especialização ou aperfeiçoamento, o militar deve permanecer no exercício das funções por:',
 'Dois anos fixos.',
 'O dobro do afastamento.',
 'Período igual ao afastamento concedido.',
 'No mínimo seis meses.',
 'Prazo fixado livremente pelo Comandante-Geral.',
 'C',
 'A permanência deve corresponder ao período do afastamento concedido.',
 'LC nº 194/2012, curso/afastamento',
 'medio'),

(@cat_prova,
 'Se o militar solicita exoneração ou aposentadoria antes de cumprir o período de permanência exigido após curso, ele:',
 'Ressarcirá proporcionalmente a corporação pelos meses faltantes.',
 'Terá a exoneração negada até completar o período.',
 'Ficará agregado até cumprir o período.',
 'Será licenciado ex-officio sem remuneração.',
 'Será exonerado sem ônus por motivo de força maior.',
 'A',
 'O descumprimento da permanência gera ressarcimento proporcional.',
 'LC nº 194/2012, curso/ressarcimento',
 'medio'),

(@cat_prova,
 'Qual hipótese NÃO é causa de desligamento ou exclusão do serviço ativo?',
 'Transferência para a reserva remunerada.',
 'Exclusão a bem da disciplina.',
 'Suspensão disciplinar por prazo determinado.',
 'Reforma administrativa disciplinar.',
 'Perda do posto e patente.',
 'C',
 'Suspensão disciplinar é temporária e não desliga o militar do serviço ativo.',
 'LC nº 194/2012',
 'facil'),

(@cat_prova,
 'O militar estadual lotado em município interiorano somente poderá ser remanejado para Boa Vista após cumprir, no mínimo:',
 'Dois anos.',
 'Cinco anos, condicionado à existência de vaga.',
 'Três anos.',
 'Quatro anos.',
 'Dez anos, independentemente de vaga.',
 'B',
 'O militar do interior só pode ser remanejado para Boa Vista após cinco anos de efetivo exercício no interior e existência de vaga.',
 'Art. 11, §1º, LC nº 194/2012',
 'dificil'),

(@cat_prova,
 'Sobre a acumulação lícita de cargo do militar estadual, assinale a correta:',
 'Somente oficiais superiores podem acumular cargos em saúde, sem restrição de horário.',
 'Apenas militares do Quadro de Saúde podem acumular qualquer cargo.',
 'Todos os militares podem acumular qualquer cargo se autorizados.',
 'É vedada qualquer acumulação.',
 'É permitida aos oficiais por formação científica e às praças por formação técnico-profissional, nas áreas de saúde ou educação, com compatibilidade de horários.',
 'E',
 'A acumulação admitida é restrita às áreas de saúde ou educação e depende de compatibilidade de horários.',
 'Art. 40, §2º, LC nº 194/2012',
 'medio'),

(@cat_prova,
 'O provimento de cargo militar se faz por nomeação de quem?',
 'Exclusivamente pelo Governador do Estado.',
 'Pelo Secretário de Segurança Pública, por delegação.',
 'Pelo Ministério da Defesa.',
 'Pelo Governador do Estado e pelos Comandantes-Gerais das respectivas instituições, conforme competência.',
 'Pela Assembleia Legislativa.',
 'D',
 'O Estatuto considera autoridades competentes o Governador e os Comandantes-Gerais das instituições.',
 'Art. 30, parágrafo único, LC nº 194/2012',
 'medio'),

(@cat_prova,
 'Assinale a alternativa que NÃO corresponde a uma hipótese de vacância do cargo público militar:',
 'Exoneração.',
 'Promoção.',
 'Ter sido considerado desertor.',
 'Suspensão disciplinar por prazo determinado.',
 'Falecimento.',
 'D',
 'Vacância decorre de exoneração, demissão, promoção, reserva, reforma, falecimento, entre outras; suspensão disciplinar não é vacância.',
 'Art. 31, LC nº 194/2012',
 'medio'),

(@cat_prova,
 'Militares nomeados para cargos no Colégio Militar Estadual ou em exercício de docência nessa unidade são considerados em função de qual natureza?',
 'Função de natureza policial militar.',
 'Função de natureza civil.',
 'Função educacional desvinculada da carreira militar.',
 'Função administrativa sujeita a regime civil.',
 'Função híbrida sem enquadramento específico.',
 'A',
 'O Estatuto enquadra esses militares como em função de natureza policial militar.',
 'Art. 37, parágrafo único, LC nº 194/2012',
 'facil'),

(@cat_prova,
 'São considerados no exercício da função militar os militares em cargo de instrutor ou aluno de estabelecimento de ensino militar ou civil, no Brasil ou Exterior, desde que:',
 'Sejam oficiais superiores ou praças com mais de dez anos.',
 'Estejam em especialização de segurança pública.',
 'Possuam autorização do Ministério da Defesa.',
 'Apresentem vínculo formal com o estabelecimento.',
 'No interesse das instituições militares a que pertencerem.',
 'E',
 'O requisito legal é que a atividade de instrutor ou aluno ocorra no interesse da instituição militar a que pertence.',
 'Art. 32, §1º, II, LC nº 194/2012',
 'facil'),

(@cat_prova,
 'Além da posse sem exercício no prazo, a exoneração de ofício também ocorre quando:',
 'O militar for condenado à reforma administrativa disciplinar.',
 'Ultrapassar dois anos em licença para interesse particular.',
 'For enquadrado genericamente no art. 131.',
 'Não satisfizer condições do estágio probatório ou o oficial se enquadrar nas condições legais específicas.',
 'For declarado desertor ou extraviado.',
 'D',
 'A exoneração de ofício alcança hipóteses de não aprovação no estágio probatório e situações específicas previstas para oficiais.',
 'LC nº 194/2012, exoneração',
 'medio'),

(@cat_prova,
 'As praças empossadas em cargo público permanente estranho à carreira serão licenciadas ex-officio sem remuneração, exceto para quais cargos?',
 'Cargos de magistério e de saúde.',
 'Cargos técnico-científicos reconhecidos pelo Comandante-Geral.',
 'Qualquer cargo público de nível superior.',
 'Cargos administrativos federais.',
 'Cargos em comissão do Governador.',
 'A',
 'A exceção indicada na legislação refere-se aos cargos de magistério e saúde, compatíveis com a acumulação lícita prevista.',
 'LC nº 194/2012, licenciamento por posse em cargo público',
 'dificil'),

(@cat_prova,
 'A exclusão a bem da disciplina é aplicada ex-officio ao Aspirante-a-Oficial ou às praças com estabilidade em quais situações?',
 'Apenas quando condenados à pena superior a seis meses pelo Conselho de Disciplina.',
 'Quando condenados pelo Conselho Permanente de Justiça ou Tribunal Civil à pena restritiva de liberdade superior a dois anos, ou por crimes contra a segurança do Estado a pena de qualquer duração, e quando incidirem nos casos que motivaram julgamento pelo Conselho de Disciplina.',
 'Apenas em crimes contra a segurança do Estado.',
 'Somente por decisão do Conselho de Disciplina, sem hipótese judicial.',
 'Apenas quando condenados por Tribunal Civil à pena superior a dois anos.',
 'B',
 'A alternativa reúne as hipóteses legais de condenação e os casos disciplinares que motivam o julgamento pelo Conselho de Disciplina.',
 'LC nº 194/2012, exclusão a bem da disciplina',
 'dificil'),

(@cat_prova,
 'De quem é a competência exclusiva para o ato de exclusão a bem da disciplina do Aspirante-a-Oficial e das Praças com estabilidade assegurada?',
 'Do Governador do Estado, por decreto.',
 'Do Secretário de Segurança Pública.',
 'Do Tribunal de Justiça Militar.',
 'Do Comandante-Geral e do Secretário, em ato conjunto.',
 'Do Comandante-Geral, com exclusividade.',
 'E',
 'O ato de exclusão a bem da disciplina, para essas categorias, é de competência exclusiva do Comandante-Geral.',
 'LC nº 194/2012, exclusão a bem da disciplina',
 'medio'),

(@cat_prova,
 'A exclusão a bem da disciplina acarreta quais consequências principais?',
 'Manutenção do grau hierárquico, sem repercussão patrimonial.',
 'Perda da graduação e exclusão das fileiras da Corporação, sem permanência no serviço ativo.',
 'Apenas transferência para a reserva remunerada.',
 'Suspensão por prazo determinado, com retorno automático.',
 'Agregação até decisão judicial.',
 'B',
 'A exclusão a bem da disciplina retira a praça das fileiras da corporação e implica perda da situação funcional correspondente.',
 'LC nº 194/2012, exclusão a bem da disciplina',
 'medio'),

(@cat_prova,
 'O que é vedado na contagem dos anos de serviço do militar estadual?',
 'Computar tempo de serviço prestado às Forças Armadas antes do ingresso.',
 'Computar qualquer superposição de tempo de serviço.',
 'Computar tempo de efetivo serviço na corporação.',
 'Computar afastamento por acidente em serviço quando previsto em lei.',
 'Computar tempo em curso de formação quando legalmente admitido.',
 'B',
 'A contagem não admite superposição: um mesmo período não pode ser contado mais de uma vez.',
 'LC nº 194/2012, contagem de tempo',
 'facil'),

(@cat_prova,
 'As recompensas dos militares estaduais consistem em quais modalidades?',
 'Apenas condecorações e elogios formais.',
 'Promoção por merecimento, condecorações e dispensas.',
 'Elogios, condecorações e dispensas do serviço.',
 'Advertência positiva e dispensa de instrução.',
 'Somente elogio individual e coletivo.',
 'C',
 'O CEDM/RR trata como recompensas, entre outras, condecorações, elogios e dispensas do serviço.',
 'CEDM/RR, recompensas',
 'facil'),

(@cat_prova,
 'Curso ou estágio superior a seis meses custeado pelo Estado: antes de 24 meses do término, a reserva a pedido depende de:',
 'Indenização de todas as despesas decorrentes do curso ou estágio.',
 'Comprovação de aplicação dos conhecimentos.',
 'Autorização do Governador sem indenização.',
 'Vedação absoluta por prazo indeterminado.',
 'Devolução parcial definida pelo Comandante-Geral.',
 'A',
 'A lei condiciona a saída antes do prazo ao ressarcimento das despesas do curso/estágio.',
 'LC nº 194/2012',
 'dificil'),

(@cat_prova,
 'As dispensas de serviço serão concedidas com qual remuneração e como serão computadas?',
 'Sem remuneração, mas computadas como tempo de serviço.',
 'Com remuneração proporcional e sem contagem de tempo.',
 'Com remuneração integral e computadas como tempo de efetivo serviço.',
 'Com remuneração parcial e contadas apenas para aposentadoria.',
 'Sem remuneração e sem contagem de tempo.',
 'C',
 'Como recompensa, a dispensa é gozada com remuneração integral e computada como tempo de efetivo serviço.',
 'CEDM/RR, dispensas de serviço',
 'facil'),

(@cat_prova,
 'Com qual finalidade e forma pode ocorrer a redução do interstício e do tempo arregimentado dos Quadros de Oficiais e Praças?',
 'Para manter renovação, equilíbrio e regularidade de acesso nos quadros, podendo ocorrer redução anual de até a metade, uma vez por ano, por ato do Governador mediante proposta do Comandante-Geral.',
 'Para punir excesso de efetivo, por ato do Secretário.',
 'Para permitir promoção sem vaga, por decisão individual.',
 'Apenas em caso de guerra ou calamidade.',
 'Somente para oficiais superiores, por lei federal.',
 'A',
 'A redução serve ao fluxo da carreira, renovação e equilíbrio dos quadros, por ato do Governador mediante proposta do Comandante-Geral.',
 'LC nº 194/2012, redução de interstício',
 'dificil'),

(@cat_prova,
 'Entre os preceitos éticos há um que determina postura de não subserviência. Qual é seu conteúdo?',
 'Abster-se do uso do posto, graduação ou função para obter facilidades.',
 'Ser fiel na vida militar, cumprindo compromissos de agente público.',
 'Conduzir-se de modo não subserviente, sem ferir os princípios de respeito e decoro.',
 'Observar direitos e garantias fundamentais.',
 'Tratar cidadãos de forma urbana e cordial.',
 'C',
 'O preceito é conduzir-se de modo não subserviente, mas sem violar respeito e decoro.',
 'Art. 20, XV, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'Qual preceito impõe postura irrepreensível na vida pública e particular?',
 'Tratar cidadãos com urbanidade.',
 'Ser fiel na vida militar.',
 'Manter ânimo forte.',
 'Observar direitos fundamentais.',
 'Proceder de maneira ilibada na vida pública e particular.',
 'E',
 'A postura ilibada é exigida na vida pública e particular.',
 'Art. 20, XXXIII, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'O oficial adquire estabilidade:',
 'No ato de sua promoção ao primeiro posto, após período mínimo de seis meses como Aspirante-a-Oficial, mediante conceito favorável.',
 'Na matrícula do curso de formação.',
 'Ao completar 3 anos, sem distinção.',
 'Na posse.',
 'Após 30 meses de estágio.',
 'A',
 'A estabilidade do oficial se dá na promoção ao primeiro posto, com período de aspirantado e conceito favorável.',
 'Art. 20, §1º, LC nº 194/2012',
 'medio'),

(@cat_prova,
 'Quantos e quais são os quadros que compõem o Quadro de Oficiais das instituições militares estaduais, segundo a redação-base da LC nº 194/2012?',
 'Quatro: QOC, QCO, QOS e QEO.',
 'Cinco: QOC, QCO, QOS, QOM e QEP.',
 'Três: QOC, QOS e QEO.',
 'Seis: QOC, QCO, QOS, QOM, QEO e QOCap.',
 'Sete, incluindo o QPC.',
 'D',
 'A redação-base lista seis quadros de oficiais: QOC, QCO, QOS, QOM, QEO e QOCap. Atenção: a LC nº 372/2026 trouxe alterações específicas nos quadros de saúde.',
 'Art. 22, I, LC nº 194/2012',
 'dificil'),

(@cat_prova,
 'As demonstrações de camaradagem, cortesia e consideração devem ser extensivas a quais profissionais?',
 'Apenas servidores civis estaduais.',
 'Somente militares federais em missão em Roraima.',
 'Cidadãos em geral.',
 'Militares das Forças Armadas e policiais e bombeiros militares de outras corporações.',
 'Apenas militares de posto ou graduação superior.',
 'D',
 'A civilidade militar deve alcançar também militares das Forças Armadas e policiais/bombeiros militares de outras corporações.',
 'Art. 17, parágrafo único, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'Entre os valores militares listados no CEDM/RR está um que exige completo devotamento à segurança pública, mesmo com risco pessoal. Qual é?',
 'Integral devotamento à preservação da ordem pública, mesmo com o risco da própria vida.',
 'Neutralidade política em todas as manifestações públicas.',
 'Subordinação irrestrita a qualquer ordem.',
 'Prevalência do interesse coletivo sobre direitos individuais em qualquer circunstância.',
 'Sigilo absoluto sobre atividades institucionais.',
 'A',
 'O valor expresso é o integral devotamento à preservação da ordem pública, mesmo com risco da própria vida.',
 'Art. 18, XVII, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'Qual alternativa descreve corretamente o Pundonor Militar?',
 'Sentimento de dignidade própria e respeito perante a comunidade.',
 'Valor moral e social da Instituição.',
 'Exercício eficiente das funções e cumprimento das leis.',
 'Observância dos preceitos morais e éticos vinculados ao cargo.',
 'Dever de pautar a conduta com correção de atitudes, exigindo comportamento ético que reflita no desempenho perante a instituição e no respeito devido.',
 'E',
 'Pundonor militar é o dever de conduta correta, digna e ética em qualquer ocasião.',
 'Art. 19, §3º, Lei nº 963/2014',
 'medio'),

(@cat_prova,
 'Qual alternativa descreve corretamente a compatibilidade para com o cargo?',
 'Observância aos preceitos morais e éticos vinculados à conduta.',
 'Sentimento de dignidade própria perante superiores, pares e subordinados.',
 'Habilitação do militar ao exercício funcional, cuja ausência por ineficiência ou inaptidão técnica causa prejuízo ao interesse público.',
 'Valor moral e social da Instituição.',
 'Exercício com autoridade e eficiência das funções do cargo.',
 'C',
 'Compatibilidade para com o cargo liga-se à habilitação funcional; sua falta por ineficiência/inaptidão técnica prejudica o interesse público.',
 'Art. 19, §6º, Lei nº 963/2014',
 'medio'),

(@cat_prova,
 'O sentimento do dever, o pundonor militar e o decoro da classe impõem aos integrantes da PM e do CBM qual conduta?',
 'Técnica e operacional irrepreensível.',
 'Moral e profissional irrepreensível.',
 'Administrativa e financeira irrepreensível.',
 'Estritamente operacional.',
 'Privada sem reflexo institucional.',
 'B',
 'O caput do art. 20 impõe conduta moral e profissional irrepreensível.',
 'Art. 20, caput, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'O CEDM/RR tem por finalidade estabelecer normas disciplinares e recompensas dos integrantes de quais instituições?',
 'Polícia Civil e Polícia Militar.',
 'Somente Corpo de Bombeiros Militar.',
 'Polícia Militar e Corpo de Bombeiros Militar do Estado de Roraima.',
 'Polícia Federal e instituições militares estaduais.',
 'Forças Armadas em Roraima.',
 'C',
 'O Código alcança integrantes da PMRR e do CBMRR.',
 'Art. 1º, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'O CEDM/RR estabelece exceção expressa quanto à sua aplicação. Quem não está sujeito ao Código e por quê?',
 'Militares da reserva remunerada, por estarem sujeitos só ao Estatuto.',
 'Alunos em estágio probatório, por ainda não serem militares.',
 'Militares cedidos a outros órgãos.',
 'Subtenentes e Sargentos administrativos.',
 'Oficiais Juízes do Tribunal de Justiça Militar Estadual, por legislação específica.',
 'E',
 'O Código exclui expressamente os Oficiais Juízes do Tribunal de Justiça Militar Estadual, regidos por legislação própria.',
 'Art. 3º, Lei nº 963/2014',
 'dificil'),

(@cat_prova,
 'Para efeito do CEDM/RR, Comandantes, Diretores ou Chefes de OM, Subunidades e Pelotões destacados recebem qual denominação?',
 'Superiores hierárquicos imediatos.',
 'Comandantes, para efeito de aplicação da Lei.',
 'Chefes de seção.',
 'Diretores operacionais.',
 'Autoridades de controle.',
 'B',
 'A lei unifica a denominação desses agentes como "Comandantes" para sua aplicação.',
 'Art. 4º, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'Na Hierarquia Militar definida pelo CEDM/RR, quem alcança o grau máximo como Comandante Supremo das Corporações?',
 'Comandante-Geral da Polícia Militar.',
 'Comandante-Geral do Corpo de Bombeiros.',
 'Secretário de Segurança Pública.',
 'Governador do Estado.',
 'Ministro da Justiça e Segurança Pública.',
 'D',
 'A hierarquia militar alcança grau máximo no Governador, Comandante Supremo da PM e do CBM.',
 'Art. 5º, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'Segundo o CEDM/RR, qual a diferença entre Posto e Graduação?',
 'Posto é conferido pelo Comandante-Geral; Graduação pelo Governador.',
 'Posto é conferido pelo Secretário de Segurança; Graduação pelo Comandante-Geral.',
 'Posto é grau dos Oficiais, conferido por ato do Governador e atestado em carta patente; Graduação é grau das Praças, conferido pelos Comandantes-Gerais.',
 'Ambos são conferidos pelo Governador.',
 'Posto é da Assembleia; Graduação é do Governador.',
 'C',
 'O Código distingue o grau dos oficiais e das praças e as autoridades que os conferem.',
 'Art. 5º, §§1º e 2º, Lei nº 963/2014',
 'medio'),

(@cat_prova,
 'O compromisso de honra no CEDM/RR é prestado em qual momento e com qual conteúdo?',
 'Ao término do curso de formação, afirmando aceitação consciente das obrigações e deveres militares e disposição de cumpri-los.',
 'Na posse, com fidelidade exclusiva à Constituição.',
 'Antes do curso, declarando aptidão física.',
 'A cada promoção.',
 'No fim do estágio probatório com permanência mínima de dez anos.',
 'A',
 'O compromisso ocorre ao término do curso de formação e envolve aceitação consciente das obrigações e deveres militares.',
 'Art. 22, Lei nº 963/2014',
 'medio'),

(@cat_prova,
 'As dispensas de serviço serão concedidas com qual remuneração e como serão computadas? (CEDM/RR)',
 'Sem remuneração, mas computadas.',
 'Com remuneração proporcional.',
 'Com remuneração integral e computadas como tempo de efetivo serviço.',
 'Com remuneração parcial e contadas só para aposentadoria.',
 'Sem remuneração e sem contagem.',
 'C',
 'Como recompensa, a dispensa não prejudica remuneração e conta como tempo de efetivo serviço.',
 'CEDM/RR, dispensas',
 'facil'),

(@cat_prova,
 'Qual alternativa reflete corretamente o emprego de Cabos e Soldados? (CEDM/RR)',
 'Prioritariamente em atividades administrativas.',
 'Assessoramento aos Oficiais.',
 'Preferencialmente em instrução.',
 'Inteligência e investigação.',
 'Prioritariamente na execução das atividades operacionais, observadas as normas dos serviços e missões.',
 'E',
 'A função típica de Cabos e Soldados, no Código, é a execução prioritária das atividades operacionais.',
 'Art. 14, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'O CEDM/RR distingue modalidades de sindicância. Qual alternativa descreve corretamente a Sindicância Inquisitorial?',
 'Apura transgressões com autoria e materialidade comprovadas, sendo a mais completa.',
 'Aplica punição diretamente.',
 'É idêntica à Sumária, mudando apenas o prazo.',
 'Tem cunho investigativo e objetiva verificar materialidade e indício de autoria, subsidiando instauração de procedimento adequado ou arquivamento.',
 'Julga definitivamente a responsabilidade do militar.',
 'D',
 'A sindicância inquisitorial é investigativa e serve para verificar materialidade e indícios de autoria.',
 'Art. 96, I, Lei nº 963/2014',
 'dificil'),

(@cat_prova,
 'Sobre o recurso disciplinar, quais são as regras de reconsideração pela autoridade que aplicou a sanção?',
 'Deve reconsiderar obrigatoriamente em 10 dias.',
 'Pode reconsiderar em 5 dias úteis, se entender procedente; caso contrário, encaminha o recurso ao destinatário com argumentos e documentação necessários.',
 'A reconsideração é vedada.',
 'A reconsideração é automática e suspende o recurso.',
 'Pode reconsiderar em qualquer prazo.',
 'B',
 'A autoridade pode reconsiderar em 5 dias úteis; se não o fizer, encaminha o recurso à autoridade competente.',
 'Art. 85, parágrafo único, Lei nº 963/2014',
 'dificil'),

(@cat_prova,
 'Sobre o elogio individual e observações positivas de autoridades civis, assinale a correta.',
 'O elogio individual somente pode ser formulado a militares que se destacaram da coletividade em ato de serviço ou ação meritória; observações positivas de autoridades ou representantes da sociedade civil serão registradas como elogio se ratificadas pela autoridade militar competente.',
 'Pode ser formulado a qualquer militar sem destaque específico; observações civis nunca geram elogio.',
 'É sempre sigiloso; observações civis só geram elogio se aprovadas pelo Governador.',
 'Só o Comandante-Geral pode elogiar; observações civis valem automaticamente.',
 'Elogios não precisam ser publicados; qualquer observação civil gera elogio automático.',
 'A',
 'O elogio exige destaque e observações civis precisam de ratificação pela autoridade militar competente.',
 'CEDM/RR, elogios e recompensas',
 'dificil'),

(@cat_prova,
 'De onde decorre exclusivamente a subordinação dos militares estaduais e o que ela não afeta?',
 'Das relações de confiança; não afeta a eficiência.',
 'Das estruturas hierarquizadas da PM e do CBM; não afeta a dignidade pessoal do militar.',
 'Das normas internas; não afeta a carreira.',
 'Do posto ou graduação; não afeta remuneração.',
 'Da antiguidade; não afeta direitos funcionais.',
 'B',
 'A subordinação decorre das estruturas hierarquizadas e não afeta a dignidade pessoal do militar.',
 'Art. 11, Lei nº 963/2014',
 'medio'),

(@cat_prova,
 'Qual afirmação descreve corretamente as funções atribuídas aos Oficiais?',
 'São preparados exclusivamente para atividades operacionais.',
 'Auxiliam superiores no adestramento.',
 'Devem ser empregados prioritariamente na execução operacional.',
 'São preparados ao longo da carreira para o exercício do comando, chefia e direção das Organizações Militares.',
 'Exercem apenas assessoramento técnico e jurídico.',
 'D',
 'Os Oficiais são preparados para comando, chefia e direção das Organizações Militares.',
 'Art. 12, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'A Ordenação da Autoridade no CEDM/RR se faz por postos e graduações conforme quais critérios?',
 'Tempo de serviço, mérito e desempenho.',
 'Formação acadêmica, especialização e antiguidade.',
 'Data de ingresso, região e escolaridade.',
 'Antiguidade, avaliação e posto.',
 'Escalonamento hierárquico, antiguidade e precedência funcional.',
 'E',
 'A ordenação segue escalonamento hierárquico, antiguidade e precedência funcional.',
 'Art. 6º, Lei nº 963/2014',
 'medio'),

(@cat_prova,
 'A Disciplina Militar é rigorosa observância das leis, regulamentos, normas e disposições. Qual afirmação está correta?',
 'Deve ser mantida apenas no serviço ativo.',
 'Disciplina e respeito à hierarquia devem ser mantidos permanentemente pelos militares na ativa e na inatividade.',
 'É exigida somente nas OM.',
 'É obrigatória apenas no horário de trabalho.',
 'É exigida apenas em missão operacional.',
 'B',
 'A disciplina e a hierarquia são permanentes, inclusive na inatividade.',
 'Art. 8º, §2º, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'Qual alternativa reflete corretamente a determinação do CEDM/RR sobre Cabos e Soldados?',
 'Devem ser empregados prioritariamente em atividades administrativas.',
 'Exercem assessoramento e suporte aos Oficiais.',
 'Devem ser empregados preferencialmente em instrução.',
 'São empregados em inteligência e investigação.',
 'Devem ser empregados prioritariamente na execução das atividades operacionais.',
 'E',
 'Cabos e Soldados são destinados prioritariamente às atividades operacionais.',
 'Art. 14, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'Qual é o objetivo específico da Deontologia Militar, conforme o parágrafo único do CEDM/RR?',
 'Fortalecer a hierarquia e disciplina interna.',
 'Promover eficiência operacional e controle disciplinar.',
 'Reunir valores úteis, lógicos e razoáveis destinados a elevar a profissão dos militares à condição de missão.',
 'Desenvolver o potencial técnico-profissional.',
 'Aplicar sanções disciplinares com justiça.',
 'C',
 'A Deontologia Militar busca elevar a profissão militar à condição de missão por meio de valores úteis, lógicos e razoáveis.',
 'Art. 15, parágrafo único, Lei nº 963/2014',
 'dificil'),

(@cat_prova,
 'Quanto à camaradagem, qual obrigação o Código impõe a todos os integrantes da PM e do CBM?',
 'Cumprir ordens sem questionamentos.',
 'Incentivar e manter a harmonia e a solidariedade entre si.',
 'Promover competições internas.',
 'Comunicar todo desvio ao superior.',
 'Participar de atividades sociais obrigatórias.',
 'B',
 'A camaradagem exige preservação das relações sociais, harmonia e solidariedade.',
 'Art. 16, parágrafo único, Lei nº 963/2014',
 'facil'),

(@cat_prova,
 'Sobre as ordens militares e suas consequências, qual afirmação está de acordo com o CEDM/RR?',
 'As ordens devem ser prontamente obedecidas, desde que não manifestamente ilegais; cabe ao militar a responsabilidade pelas ordens que der e consequências delas.',
 'Ordens só são obedecidas após análise técnica do subordinado.',
 'O subordinado não pode pedir esclarecimentos.',
 'A responsabilidade por ordens ilegais é sempre do subordinado.',
 'Se terceiro civil provoca violação disciplinar, responde disciplinarmente perante a corporação.',
 'A',
 'A obediência é pronta, mas limitada pela legalidade; o superior responde pelas ordens que dá e suas consequências.',
 'Art. 9º, Lei nº 963/2014',
 'medio'),

(@cat_prova,
 'Qual afirmação reflete corretamente a natureza e os efeitos do Comando no CEDM/RR?',
 'É personalíssimo e não vinculado ao grau hierárquico.',
 'É atribuído exclusivamente a Oficiais, sem equiparação a chefias.',
 'Só pode ser exercido por outorga expressa do Governador.',
 'Constitui prerrogativa impessoal vinculada ao grau hierárquico; equipara-se a comandante toda autoridade militar com função de direção e chefia.',
 'Exige presença física na OM e se suspende em afastamento.',
 'D',
 'O comando é prerrogativa impessoal vinculada ao grau hierárquico e abrange autoridades militares em função de direção e chefia.',
 'Art. 10, §§1º e 2º, Lei nº 963/2014',
 'dificil'),

(@cat_prova,
 'Qual obrigação dos Subtenentes e Sargentos em relação às Praças diretamente subordinadas está correta?',
 'Assegurar a observância minuciosa e ininterrupta das ordens, regras do serviço e normas operativas, e manter a coesão e a moral em todas as circunstâncias.',
 'Apenas avaliar desempenho e enviar relatórios.',
 'Aplicar sanções sem comunicar oficial.',
 'Substituir oficiais no comando sempre que necessário.',
 'Apenas executar atividades operacionais sem responsabilidade sobre subordinados.',
 'A',
 'O Código atribui aos Subtenentes e Sargentos papel direto na disciplina, coesão, moral e observância das normas pelas Praças subordinadas.',
 'Art. 13, parágrafo único, Lei nº 963/2014',
 'medio');

SET foreign_key_checks = 1;
