-- ============================================================
-- PROVA 3 — 40 Questões de Casos Práticos
-- Estatuto dos Militares (LC nº 194/2012) + CEDM/RR (Lei nº 963/2014) + LC nº 372/2026
-- Todas as questões: nível "dificil", com histórias/casos práticos
-- ============================================================
SET NAMES utf8mb4;
SET foreign_key_checks = 0;

-- Criar categoria Prova 3
INSERT IGNORE INTO categorias (nome, descricao)
VALUES ('🎯 Prova 3', 'Casos Práticos — Estatuto (LC 194/2012), CEDM/RR (Lei 963/2014) e LC 372/2026');

SET @cat_p3 = (SELECT id FROM categorias WHERE nome = '🎯 Prova 3' LIMIT 1);

INSERT INTO questoes
    (categoria_id, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, opcao_e,
     resposta_correta, explicacao, referencia_legal, nivel)
VALUES

-- Q1: Progressão no QEP
(@cat_p3,
 'O Soldado QPC PM Marcos ingressou na corporação há exatos 6 (seis) anos. Ele possui o comportamento classificado como "Bom" e, ao ver a abertura de um edital com vagas disponíveis, requer sua matrícula no Curso de Formação de Cabos (CFC) para ingressar no Quadro Especial de Praças (QEP PM/BM). À luz das regras atualizadas em 2026, o pleito do Soldado Marcos é procedente?',
 'Não, pois o tempo mínimo exigido para o Soldado pleitear o CFC é de 8 anos de efetivo serviço.',
 'Sim, pois o tempo mínimo foi reduzido para 5 anos de efetivo serviço, desde que cumpra os demais requisitos de comportamento e vaga.',
 'Não, pois a lei exige comportamento mínimo "Ótimo" para ingresso no QEP.',
 'Sim, mas ele precisará averbar tempo de serviço civil para alcançar o interstício mínimo de 10 anos.',
 'Não, pois o QEP foi extinto para os Soldados combatentes.',
 'B',
 'A LC nº 372/2026 alterou o Art. 71-A, §1º, do Estatuto, reduzindo o tempo exigido para que o Soldado pleiteie o CFC. Agora, ao completar 5 (cinco) anos de tempo de efetivo serviço, estando no mínimo no comportamento "bom", observada a antiguidade e a disponibilidade de vaga, ele fará jus à promoção.',
 'Art. 71-A, §1º, LC 194/2012 (Redação da LC 372/2026)',
 'dificil'),

-- Q2: Conversão de Punição e Frações de Dia
(@cat_p3,
 'O 3º Sargento Vieira cometeu uma transgressão disciplinar média isolada (sua primeira na carreira) e foi punido com 7 (sete) dias de Permanência Disciplinar. Como ele possui comportamento "Ótimo", solicitou ao Comandante a conversão da punição em prestação de serviço operacional. O Comandante deferiu o pedido. Quantos turnos operacionais (de no mínimo 8h e máximo 12h) o Sargento Vieira deverá cumprir?',
 '4 turnos, pois a fração deve ser arredondada para cima.',
 '3 turnos e meio.',
 '3 turnos operacionais.',
 '7 turnos operacionais, pois a equivalência é de um para um.',
 'A punição não pode ser convertida, pois trata-se de transgressão média.',
 'C',
 'De acordo com o CEDM (Lei nº 963/2014), Art. 67, §5º, considera-se 1 turno de prestação de serviço operacional equivalente a 2 dias de sanção. O §8º determina que em caso de número ímpar de dias, será arredondado para menos. Portanto, 7 dias arredondados para menos = 6 dias ÷ 2 = 3 turnos operacionais.',
 'Art. 67, §§5º e 8º, Lei nº 963/2014',
 'dificil'),

-- Q3: Extensão de Carreira do QEO
(@cat_p3,
 'O Capitão QEO PM Farias possui 24 anos de tempo de efetivo serviço na corporação e almeja alcançar o posto de Tenente-Coronel antes de ir para a reserva. De acordo com a atualização do Estatuto dos Militares (LC 372/2026), quais são os requisitos exatos de tempo e curso para que ele chegue ao posto de Major QEO e, futuramente, ao posto de Tenente-Coronel QEO?',
 'Ele não pode passar de Capitão, pois o QEO é limitado a este posto.',
 'Para Major: 25 anos de serviço + Curso de Aperfeiçoamento de Oficiais (CAO). Para Tenente-Coronel: 27 anos de serviço.',
 'Para Major: 24 anos de serviço + Curso Superior. Para Tenente-Coronel: 30 anos de serviço.',
 'Para Major: 25 anos de serviço (independente de curso). Para Tenente-Coronel: 29 anos e 6 meses.',
 'Para ambos os postos exige-se apenas a promoção excepcional na data de transferência para a inatividade.',
 'B',
 'A LC nº 372/2026 modificou a estrutura do QEO no Art. 71-A. Para Major QEO: 25 anos de efetivo serviço + CAO. Para Tenente-Coronel QEO: 27 anos de efetivo serviço.',
 'Art. 71-A, LC 194/2012 (Redação da LC 372/2026)',
 'dificil'),

-- Q4: Averbação de Tempo Civil
(@cat_p3,
 'O Subtenente PM Mendes trabalhou 4 anos na Prefeitura de Boa Vista como guarda civil antes de ingressar na PMRR. Hoje ele tem 16 anos de PMRR. Ele protocola requerimento pedindo para somar os 4 anos civis aos seus 16 militares, totalizando 20 anos, a fim de preencher o requisito de "Tempo de Efetivo Serviço" e ser matriculado no Curso de Habilitação de Oficiais (CHO). O pedido de Mendes está amparado pelo Estatuto (LC 194/2012)?',
 'Sim, desde que haja certidão do INSS comprovando os 4 anos.',
 'Não, pois o tempo civil anterior à corporação é considerado "Anos de Serviço" e não "Tempo de Efetivo Serviço", servindo apenas para a inatividade e não para requisitos de promoção regular na ativa.',
 'Sim, pois a lei proíbe superposição, mas não proíbe a soma de períodos distintos.',
 'Não, pois militares não podem averbar tempo civil sob nenhuma circunstância.',
 'Sim, desde que o Governador autorize a equivalência do serviço civil.',
 'B',
 'O "Tempo de Efetivo Serviço" é estritamente o tempo computado, dia a dia, do ingresso na corporação até o desligamento. O tempo civil anterior enquadra-se como "Anos de Serviço/Tempo de Contribuição" (Art. 144, I). O §1º do Art. 144 estabelece que esses acréscimos só serão computados na passagem para a inatividade, não servindo para ingresso no CHO.',
 'Art. 144, I e §1º, LC 194/2012',
 'dificil'),

-- Q5: Cautelar de Recolhimento vs Punição
(@cat_p3,
 'O Soldado Roberto, durante seu dia de folga e em trajes civis, embriaga-se em um bar, saca sua arma funcional e começa a proferir ameaças, gerando risco iminente de morte a terceiros. O Oficial de Dia chega ao local, desarma o Soldado e decreta imediatamente o seu "Recolhimento Disciplinar Cautelar", levando-o à unidade militar, onde o Soldado permanece recolhido por 4 (quatro) dias seguidos. O procedimento adotado pelo Oficial de Dia foi totalmente legal segundo o CEDM/RR?',
 'Sim, o recolhimento foi legal e pode durar até 10 dias.',
 'Não. O Oficial acertou na medida (Recolhimento Cautelar), mas errou no prazo, pois a lei impõe um limite máximo inultrapassável de 03 (três) dias para essa medida provisória.',
 'Não, pois recolhimento cautelar só se aplica a militares fardados em serviço.',
 'Sim, pois o recolhimento equivale à prisão administrativa sem limite de prazo.',
 'Não. O Oficial deveria aplicar a punição de Detenção Disciplinar diretamente no local.',
 'B',
 'O Recolhimento Disciplinar Cautelar é cabível em casos de embriaguez, agressividade ou perigo concreto à vida (Art. 61, I e III). Porém, a lei estabelece um limite estrito: o recolhimento cautelar não excederá o prazo de 03 (três) dias computados de sua efetivação. O Oficial errou ao manter o militar recolhido por 4 dias.',
 'Art. 61, I e III, Lei nº 963/2014',
 'dificil'),

-- Q6: Rito Processual e Estabilidade
(@cat_p3,
 'O Cabo PM Teixeira possui 2 (dois) anos e 6 (seis) meses de serviço ativo na corporação. Ele é acusado de uma grave infração moral (extorsão) que, em tese, o torna incompatível com as fileiras da PMRR. O Comandante deseja submetê-lo a um processo regular para, se for o caso, excluí-lo da corporação. A qual instrumento de processo regular o Cabo Teixeira deverá ser submetido, conforme o CEDM/RR?',
 'Conselho de Disciplina.',
 'Conselho de Justificação.',
 'Processo Administrativo Disciplinar (PAD).',
 'Sindicância Inquisitorial.',
 'Exclusão direta ex-officio sem processo, pois não possui estabilidade.',
 'C',
 'O PAD é o instrumento destinado ao julgamento das Praças sem estabilidade (com menos de 3 anos de serviço), com o objetivo de verificar se possuem condições éticas e morais para permanecer nas fileiras da Corporação (Art. 92, III, e Art. 95 do CEDM). O Conselho de Disciplina é restrito às Praças com estabilidade.',
 'Arts. 92, III e 95, Lei nº 963/2014',
 'dificil'),

-- Q7: Afastamento por Núpcias e União Estável
(@cat_p3,
 'O 1º Tenente PM Carlos formalizou sua união estável em cartório com Maria em março de 2024 e solicitou os 8 dias de afastamento (núpcias), os quais foram deferidos. Dois anos depois, em maio de 2026, Carlos e Maria decidem converter a união estável em casamento civil formal. Carlos protocola novo pedido de afastamento de 8 dias para a licença nupcial pelo casamento. A administração militar deve conceder a nova licença de núpcias?',
 'Sim, pois o casamento civil é um ato jurídico distinto da união estável.',
 'Não, pois a licença núpcias só é concedida uma única vez em toda a carreira militar.',
 'Sim, mas descontada da sua cota anual de férias.',
 'Não, pois a lei veda apresentar certidão de casamento com o mesmo cônjuge se o militar já tiver gozado o afastamento por meio da declaração de união estável.',
 'Sim, desde que o casamento ocorra após 2 anos da união estável.',
 'D',
 'O Estatuto é claro no Art. 75, §1º, alínea "a": o militar que apresentar declaração de união estável para o gozo do afastamento por motivo de núpcias, não poderá posteriormente apresentar certidão de casamento constando o nome do mesmo cônjuge para fins desse afastamento.',
 'Art. 75, §1º, "a", LC 194/2012',
 'dificil'),

-- Q8: Requisitos de Ingresso no CHO
(@cat_p3,
 'A Subtenente QEP PM Joana atingiu o tempo necessário (19 anos) e obteve a antiguidade requerida para ingressar no Curso de Habilitação de Oficiais (CHO). Contudo, ela possui apenas o Ensino Médio completo. O Comando da PMRR convoca Joana apenas na condição de "ouvinte". Esta conduta da administração (convocação como ouvinte) possui amparo legal no Estatuto dos Militares? Por quê?',
 'Não. Joana deveria ser matriculada como aluna regular, pois o requisito de escolaridade para Subtenentes do QEP é apenas o Ensino Médio.',
 'Sim. O Estatuto exige, no ato da matrícula no CHO, a comprovação de Curso Superior reconhecido pelo MEC. Por não possuir o diploma, ela não atende ao requisito legal para matrícula regular como aluna oficial.',
 'Não. Militares sem curso superior devem ser compulsoriamente passados para a reserva remunerada ao atingirem o topo da carreira de Praça.',
 'Sim, pois o ingresso no CHO ocorre exclusivamente por mérito intelectual em prova interna, reprovando automaticamente quem não tem diploma civil.',
 'Sim, pois a condição de "ouvinte" permite que ela seja promovida a 2º Tenente ganhando 50% do subsídio.',
 'B',
 'Conforme o Art. 22, §17 da LC 194/2012, o ingresso no CHO exige, no ato da matrícula, a comprovação de Curso Superior reconhecido ou autorizado pelo MEC. Como Joana possui apenas o Ensino Médio, ela não atende ao requisito indispensável para matrícula regular.',
 'Art. 22, §17, LC 194/2012',
 'dificil'),

-- Q9: Prazos e Regras de Transição
(@cat_p3,
 'O 1º Tenente PM Pedro foi promovido a este posto em fevereiro de 2025. Em fevereiro de 2026 (12 meses depois), abrem-se vagas para o posto de Capitão no seu quadro. Pedro pleiteia a promoção argumentando ter comportamento excelente e os cursos necessários. De acordo com as disposições temporárias fixadas pela LC 372/2026, Pedro pode ser promovido a Capitão nesta data?',
 'Sim, o interstício exigido de 1º Tenente para Capitão é de exatos 12 meses.',
 'Sim, o interstício não se aplica quando houver claro (vaga) no quadro.',
 'Não, pois a regra transitória de 2026 estabeleceu que o interstício mínimo do posto de 1º Tenente para Capitão é de 24 (vinte e quatro) meses.',
 'Não, pois ele precisa de 36 (trinta e seis) meses de interstício para essa promoção.',
 'Sim, desde que preste prova de mérito intelectual.',
 'C',
 'A LC 372/2026 introduziu uma regra de transição (Art. 73-B, parágrafo único) determinando que, enquanto não houver uma nova Lei de Promoção, o interstício obrigatório para promoção de 1º Tenente para Capitão é de 24 meses. Como Pedro tinha apenas 12 meses, ele não preenche o requisito.',
 'Art. 73-B, parágrafo único, LC 194/2012 (Redação da LC 372/2026)',
 'dificil'),

-- Q10: Prescrição da Sanção
(@cat_p3,
 'O Cabo PM João foi processado administrativamente por uma transgressão média. A solução definitiva com a aplicação da pena de 8 dias de Permanência Disciplinar foi publicada em 10 de maio de 2023. Devido a uma desorganização na Unidade, o Cabo nunca foi chamado para cumprir a punição. Em 15 de junho de 2024, o novo Comandante manda executar a punição imediatamente. O Cabo João é obrigado a cumprir a sanção disciplinar?',
 'Sim, pois as sanções disciplinares militares são imprescritíveis.',
 'Sim, pois o prazo para cumprimento da pena é de 5 anos após a publicação.',
 'Não, pois prescreveu. O direito de aplicar/executar a sanção disciplinar prescreve em 01 (um) ano após a solução definitiva se ela não for executada.',
 'Não, pois prescreve em 06 (seis) meses se a punição for apenas de permanência disciplinar.',
 'Sim, desde que haja portaria de restauração assinada pelo Governador.',
 'C',
 'O CEDM/RR (Art. 97, III) prevê que o direito de punir prescreve em 01 ano após a solução definitiva se não ocorrer a aplicação da sanção disciplinar. Como a punição foi publicada em maio de 2023 e só tentaram executá-la em junho de 2024 (mais de um ano depois), ocorreu a prescrição.',
 'Art. 97, III, Lei nº 963/2014',
 'dificil'),

-- Q11: Comportamento e Equivalência de Punições
(@cat_p3,
 'O Cabo PM Santos, que possuía 3 anos de serviço, cometeu três pequenas falhas disciplinares ao longo do último ano. Como punição, ele recebeu duas (2) Repreensões e uma (1) Permanência Disciplinar. Após o cumprimento das punições, em qual classificação de comportamento o Cabo Santos deverá ser enquadrado, segundo o CEDM/RR?',
 'Comportamento Mau.',
 'Comportamento Insuficiente.',
 'Comportamento Bom.',
 'Comportamento Ótimo.',
 'Comportamento Excepcional.',
 'C',
 'Pela regra de equivalência (Art. 76, I), 2 Repreensões = 1 Permanência Disciplinar. Logo, o Cabo possui o equivalente a 2 Permanências. Como 2 Permanências equivalem a 1 Detenção (Art. 76, III), a ficha dele soma 1 Detenção. O Art. 74, III do CEDM diz que o militar com até 2 anos de serviço punido com até duas Detenções fica no comportamento "Bom".',
 'Arts. 74, III e 76, I e III, Lei nº 963/2014',
 'dificil'),

-- Q12: Exceção à Regra de Tatuagens
(@cat_p3,
 'O 1º Sargento PM Carlos, com 21 anos de efetivo serviço na corporação, decide fazer uma tatuagem cobrindo todo o seu braço direito, visível com o uniforme de verão (manga curta). A tatuagem é um desenho tribal comum, sem alusão a crimes ou violência. O Comandante instaura procedimento para puni-lo. A conduta do Comandante está correta à luz do Estatuto dos Militares de Roraima?',
 'Sim, pois é vedada tatuagem visível no uniforme de verão para qualquer militar.',
 'Não, pois a proibição de tatuagens visíveis aplica-se apenas a desenhos ofensivos.',
 'Sim, pois tatuagens visíveis configuram transgressão grave de insubordinação.',
 'Não, pois a proibição de tatuagem visível no uniforme de verão não se aplica aos militares da ativa que possuam 20 anos ou mais de efetivo serviço.',
 'Sim, a menos que ele utilize camisas de manga longa em caráter definitivo.',
 'D',
 'O Art. 17, §6º, III proíbe o ingresso de candidatos com tatuagens visíveis no uniforme de verão. Contudo, o §7º traz uma exceção expressa: essa restrição não se aplica ao militar da ativa que contar com 20 anos ou mais de Tempo de Efetivo Serviço. Como Carlos tem 21 anos, ele está isento.',
 'Art. 17, §7º, LC 194/2012',
 'dificil'),

-- Q13: Progressão no QEP (Sargentos)
(@cat_p3,
 'O Cabo QEP PM Lima, recém-promovido, planeja o seu futuro na corporação. Ele sabe que a LC 372/2026 alterou diversos interstícios e prazos. Quantos anos de efetivo serviço o Cabo Lima precisará completar para fazer jus à matrícula no Curso de Formação de Sargentos (CFS) e qual o tempo exigido para ir de 3º para 2º Sargento QEP?',
 '12 anos para o CFS e 14 anos para 2º Sargento.',
 '10 anos para o CFS e 13 anos para 2º Sargento.',
 '8 anos para o CFS e 11 anos para 2º Sargento.',
 '5 anos para o CFS e 8 anos para 2º Sargento.',
 '12 anos para o CFS e 15 anos para 2º Sargento.',
 'C',
 'A LC 372/2026 alterou o Art. 71-A do Estatuto, reduzindo os tempos para o QEP. O §2º passou a exigir 8 anos de efetivo serviço para o Cabo pleitear o CFS (antes eram 10). E o §3º passou a exigir 11 anos de efetivo serviço para o 3º Sargento QEP ser promovido a 2º Sargento QEP (antes eram 13).',
 'Art. 71-A, §§2º e 3º, LC 194/2012 (Redação da LC 372/2026)',
 'dificil'),

-- Q14: Acidente em Serviço e Pensão/Reforma
(@cat_p3,
 'O Cabo PM Matias sofreu um grave acidente durante uma perseguição policial (em serviço), ficando tetraplégico e precisando de assistência permanente. O processo de reforma por incapacidade definitiva é concluído. Como serão calculados os proventos da reforma do Cabo Matias?',
 'Integrais, calculados com base no soldo de 3º Sargento, acrescidos de 25% por necessitar de assistência permanente.',
 'Integrais, calculados com base no soldo de 1º Sargento, acrescidos de 25% por necessitar de assistência permanente.',
 'Proporcionais ao tempo de serviço, com base no soldo de Cabo, acrescidos de 25%.',
 'Integrais, com base no soldo de Cabo, sem acréscimos.',
 'Proporcionais, com base no soldo de 3º Sargento, acrescidos de 50%.',
 'B',
 'Se a incapacidade definitiva decorre de acidente em serviço, a reforma é integral e com remuneração do grau hierárquico superior (Art. 120). O Art. 120, §1º, alínea "g": para Cabos e Soldados de 1ª classe, o grau superior considerado é o de 1º Sargento. O Art. 123-C, §4º, garante o acréscimo de 25% caso necessite de assistência permanente.',
 'Arts. 120, §1º, "g" e 123-C, §4º, LC 194/2012',
 'dificil'),

-- Q15: Gravidez no Curso de Formação
(@cat_p3,
 'A Aluna Soldado PM Beatriz engravidou no segundo mês do Curso de Formação de Soldados (CFSD), cujas atividades físicas são incompatíveis com a gestação. Qual o procedimento administrativo obrigatório a ser adotado pela corporação?',
 'Desligá-la definitivamente do concurso, por descumprimento de requisito de aptidão física.',
 'Mantê-la no curso apenas como ouvinte teórica, graduando-a sem a nota de educação física.',
 'Afastá-la do curso, garantindo seu reingresso no próximo curso ofertado após cessado o impedimento, sendo vedada a reclassificação de sua antiguidade.',
 'Transferi-la para o quadro administrativo, garantindo a promoção a soldado sem curso.',
 'Conceder licença-maternidade de 180 dias e aprová-la no curso por antiguidade.',
 'C',
 'O Art. 18, §5º, do Estatuto é taxativo: se houver gravidez durante o curso, a militar deve ser afastada, mas o Estado garante o direito de voltar no próximo curso, sendo vedada a reclassificação (ela não perde a antiguidade da turma original).',
 'Art. 18, §5º, LC 194/2012',
 'dificil'),

-- Q16: Recurso Disciplinar
(@cat_p3,
 'O Soldado PM Silva foi punido com 5 dias de permanência disciplinar. Inconformado, ele decide interpor Recurso Disciplinar ao escalão superior. Qual o prazo legal para a interposição do recurso e qual o efeito jurídico dele sobre o cumprimento da sanção?',
 '10 dias corridos, sem efeito suspensivo.',
 '5 dias corridos, com efeito devolutivo apenas.',
 '5 dias úteis, com efeito suspensivo automático.',
 '3 dias úteis, com efeito suspensivo a critério do comandante.',
 '15 dias corridos, sem efeito suspensivo.',
 'C',
 'O Art. 84 do CEDM/RR determina que da decisão que aplicar sanção caberá recurso no prazo de 05 dias úteis, contados do primeiro dia útil pós-publicação, com efeito suspensivo (a punição não é cumprida enquanto o recurso não for julgado).',
 'Art. 84, Lei nº 963/2014',
 'dificil'),

-- Q17: Agregação (Prazos)
(@cat_p3,
 'O 1º Sargento PM Mendes adoeceu de uma patologia não relacionada ao serviço, necessitando de longo tratamento médico ininterrupto. Após quanto tempo contínuo de licença médica o Sargento será considerado Agregado? E qual a consequência após 2 anos de agregação?',
 'Agregado após 6 meses. Reforma ex-officio se ultrapassar 2 anos.',
 'Agregado após 12 meses. Exclusão se ultrapassar 2 anos.',
 'Agregado após 30 dias. Reforma se ultrapassar 1 ano.',
 'Agregado após 6 meses. Licenciamento se ultrapassar 2 anos.',
 'Agregado após 2 anos. Reforma se ultrapassar 3 anos.',
 'A',
 'O militar é agregado ao ultrapassar 06 meses contínuos de licença para tratamento de saúde própria (Art. 100, §1º, III, "c"). Caso a incapacidade permaneça por mais de 2 anos, o Art. 116 determina a passagem para a Reforma.',
 'Art. 100, §1º, III, "c" e Art. 116, LC 194/2012',
 'dificil'),

-- Q18: Prescrição e Interrupção (Fuga)
(@cat_p3,
 'O Soldado João cometeu transgressão grave e responde a um PAD. Faltando 1 mês para o PAD prescrever, João foge da sua unidade (desertor), paralisando o processo, e só é capturado 2 anos depois. O advogado de defesa pede o arquivamento por prescrição. A alegação de prescrição é procedente?',
 'Sim, pois o prazo prescricional de 2 anos flui ininterruptamente, não se suspendendo por fuga.',
 'Não, pois os prazos prescricionais consideram-se suspensos por motivo de obstáculo judicial ou administrativo.',
 'Sim, pois o PAD prescreve em 1 ano, não em 2.',
 'Não, pois transgressões graves são imprescritíveis.',
 'Sim, desde que o Governador autorize a prescrição.',
 'B',
 'O Art. 97, Parágrafo único, do CEDM/RR prevê expressamente que os prazos prescricionais "consideram-se suspensos por motivo de força maior, obstáculo judicial ou administrativo, devidamente comprovado e certificado nos autos." A fuga impede a continuidade do rito, suspendendo a prescrição.',
 'Art. 97, Parágrafo único, Lei nº 963/2014',
 'dificil'),

-- Q19: Licença Adoção
(@cat_p3,
 'A 3º Sargento PM Carla obteve a guarda judicial definitiva de uma criança de 4 anos de idade. Ao solicitar a licença para cuidar do filho, o setor de RH negou o prazo de 90 dias, concedendo um período menor. Qual é o prazo correto de licença remunerada a ser concedido à Sargento Carla?',
 '180 dias.',
 '120 dias.',
 '90 dias.',
 '30 dias.',
 '15 dias.',
 'D',
 'O Art. 84 do Estatuto prevê regra dependendo da idade da criança adotada. Se a criança tem até 12 meses, a licença é de 90 dias. Contudo, o Parágrafo único determina que no caso de adoção de criança com mais de 12 meses de idade, o prazo é de 30 dias. Como a criança tem 4 anos, a licença é de 30 dias.',
 'Art. 84, Parágrafo único, LC 194/2012',
 'dificil'),

-- Q20: Excedente por Decisão Judicial
(@cat_p3,
 'O 1º Tenente PM Lucas aciona a Justiça para ser promovido a Capitão (ressarcimento de preterição), ganhando a causa. Como o Quadro de Capitães já estava 100% completo, Lucas é promovido mesmo não havendo vaga livre. Em qual situação o Capitão Lucas será posicionado, e o que ocorre na primeira vaga que abrir?',
 'Ele fica Agregado e não concorre a nada até abrir vaga.',
 'Ele se torna Excedente. Ocupa posição em antiguidade normal e receberá a primeira vaga que se verificar no quadro.',
 'Ele vai para a Reserva Remunerada proporcional, por falta de vaga.',
 'O Capitão mais moderno do quadro é rebaixado para Tenente para dar a vaga a Lucas.',
 'Ele se torna Adido e não pode receber promoções futuras.',
 'B',
 'O Art. 106, III, do Estatuto determina que passa à situação de "Excedente" o militar promovido em ressarcimento de preterição com quadro completo. O §1º garante que o excedente continua concorrendo normalmente e absorve a primeira vaga que abrir.',
 'Art. 106, III e §1º, LC 194/2012',
 'dificil'),

-- Q21: Transgressão na Frente do Público
(@cat_p3,
 'Durante uma abordagem de trânsito em praça pública lotada, o Cabo PM Marcos e o Soldado PM Tiago entram em uma discussão acalorada (ofendendo-se moralmente). A conduta de travar discussão e ofender-se moralmente (Transgressão Grave) cometida na frente da população atrai qual consequência jurídica na dosimetria da pena?',
 'É causa de justificação por estresse de serviço.',
 'É circunstância atenuante por evitar mal maior ao civil abordado.',
 'É circunstância agravante, por ter sido cometida na presença de público.',
 'Desclassifica a transgressão de Grave para Média.',
 'Implica em demissão automática por quebra do Pundonor.',
 'C',
 'O CEDM (Art. 39, X) lista expressamente que a "prática da transgressão em presença de público" é uma Circunstância Agravante.',
 'Art. 39, X, Lei nº 963/2014',
 'dificil'),

-- Q22: Atividades de Raio-X
(@cat_p3,
 'A 1º Tenente QOS (Odontóloga) Maria opera diariamente e de forma permanente equipamentos de Raios-X no serviço odontológico da corporação. Quais são as garantias exclusivas de jornada e férias asseguradas a essa militar pela lei roraimense?',
 'Jornada de 40 horas e férias de 30 dias com dobro do salário.',
 'Jornada máxima de 24 horas semanais de trabalho e férias de 20 dias consecutivos por semestre (não acumuláveis).',
 'Jornada máxima de 20 horas semanais e férias anuais normais (30 dias).',
 'Jornada reduzida a critério do comandante e adicional de 10%.',
 'Não há legislação específica; segue a regra administrativa normal.',
 'B',
 'Militares expostos a radiação (Art. 59, XXI) têm direito a regime máximo de 24 horas semanais, 20 dias de férias a cada 6 meses (não acumuláveis) e gratificação de 40%.',
 'Art. 59, XXI, "a" e "b", LC 194/2012',
 'dificil'),

-- Q23: Transgressão Conexa
(@cat_p3,
 'O Soldado Freitas, para acobertar que causou dano à viatura por imperícia (falta Média), falsifica as informações no relatório de ocorrência — mentindo intencionalmente à administração (falta Grave). Ele responderá em um PAD. No julgamento disciplinar, como o Comandante deverá tratar essas duas transgressões praticadas em conjunto pelo mesmo motivo?',
 'Como duas punições separadas, somando-se os dias de ambas.',
 'A de menor gravidade (Média) será absorvida, isentando-o de culpa.',
 'A de menor gravidade (dano na viatura) será considerada como circunstância agravante da transgressão principal (falsidade no relatório).',
 'Como foi para acobertar falha própria, a falta grave cai para média.',
 'A falsidade é justificada pelo direito constitucional de não produzir prova contra si mesmo.',
 'C',
 'O Art. 53, §7º, do CEDM dita a "Regra da Conexão": havendo mais de uma transgressão conexas, as de menor gravidade se tornam circunstâncias agravantes para elevar a punição da transgressão principal.',
 'Art. 53, §7º, Lei nº 963/2014',
 'dificil'),

-- Q24: Candidatura Política
(@cat_p3,
 'O Cabo PM Souza, que tem 8 (oito) anos de efetivo serviço na PMRR, decide se candidatar a Vereador em seu município. Seu registro de candidatura é deferido pela Justiça Eleitoral. O que acontece imediatamente com o Cabo Souza nas fileiras da Corporação?',
 'Será agregado, recebendo remuneração proporcional, até o final da eleição.',
 'Será licenciado ex-officio, por contar com menos de 10 anos de serviço.',
 'Ficará afastado temporariamente sem remuneração, podendo retornar se perder a eleição.',
 'Será transferido compulsoriamente para o Quadro Especial de Praças (QEP).',
 'Será demitido por crime de insubordinação.',
 'B',
 'Se a Praça tem menos de 10 anos de serviço e registra candidatura, ela é imediatamente licenciada ex-officio (excluída definitivamente).',
 'Art. 132, §3º, "b", LC 194/2012',
 'dificil'),

-- Q25: Conselho de Justificação
(@cat_p3,
 'O Capitão PM Augusto é submetido ao Conselho de Justificação. Ao final do rito, o Tribunal de Justiça o declara "Indigno do Oficialato". Qual sanção deve ser aplicada e quem a efetiva?',
 'Exclusão a bem da disciplina, efetivada pelo Comandante-Geral.',
 'Licenciamento, efetivado pelo Secretário de Segurança Pública.',
 'Reforma Administrativa, efetivada pela Junta Médica.',
 'Demissão (perda do posto e patente), efetivada por ato do Governador do Estado.',
 'Permanência disciplinar de 30 dias, efetivada pelo Governador.',
 'D',
 'Quando um Oficial é declarado indigno pelo Tribunal após Conselho de Justificação, a punição é a Demissão. O ato final cabe exclusivamente ao Governador.',
 'Arts. 49 e 27, I, Lei nº 963/2014',
 'dificil'),

-- Q26: Férias em Dobro
(@cat_p3,
 'O Subtenente PM Xavier passou o ano de 2024 inteiro sem tirar férias devido a intensas operações na fronteira (imperiosa necessidade do serviço, decidida fundamentadamente pelo Comando). Em 2025, ele solicita tirar os dois períodos (60 dias) acumulados. A acumulação solicitada é legalmente permitida?',
 'Não, férias militares são impreterivelmente anuais e inacumuláveis.',
 'Sim, a lei permite o acúmulo de até 2 períodos (dois anos) exclusivamente em caso de imperiosa necessidade do serviço.',
 'Não, ele perdeu as férias de 2024 e terá direito apenas a convertê-las em pecúnia.',
 'Sim, o militar pode acumular quantos anos desejar.',
 'Não, pois apenas oficiais possuem o direito de acúmulo de férias.',
 'B',
 'O §7º do Art. 74 abre uma exceção estrita: "Só será permitida a acumulação de férias até o prazo máximo de dois anos, no caso de imperiosa necessidade de serviço, por decisão devidamente fundamentada".',
 'Art. 74, §7º, LC 194/2012',
 'dificil'),

-- Q27: Suspensão de Afastamentos
(@cat_p3,
 'O 1º Tenente PM Vieira está em seu primeiro dia de férias na praia. Contudo, surge uma gravíssima denúncia, com provas robustas, de que ele cometeu um crime militar. O Comandante-Geral decide suspender as férias dele para submetê-lo a IPM. A suspensão das férias pelo Comandante-Geral possui amparo no Código de Ética?',
 'Não, férias são direito adquirido inviolável.',
 'Não, a suspensão só pode ocorrer por decretação de Estado de Sítio.',
 'Sim. O Art. 55 do CEDM autoriza a suspensão de licenças e afastamentos, a critério do Governador ou Comandante-Geral, para submeter o militar a Inquérito Policial Militar ou processo administrativo.',
 'Sim, mas apenas mediante ordem judicial (mandado).',
 'Não, o inquérito deverá correr à revelia até o seu retorno.',
 'C',
 'O Art. 55 do CEDM garante que as autoridades máximas têm o poder de cancelar o gozo de folga/licença de quem precisa responder a processo ou IPM.',
 'Art. 55, Lei nº 963/2014',
 'dificil'),

-- Q28: Licença Especial e Conversão
(@cat_p3,
 'O Sargento Silva completou 10 anos de efetivo serviço e adquiriu o direito a dois períodos (6 meses no total) de Licença Especial (quinquênios), não gozando nenhum deles. Aos 12 anos de serviço, pede exoneração para assumir cargo civil no Judiciário. O que acontecerá com o tempo de Licença Especial não gozado?',
 'Será perdido integralmente, pois o licenciamento a pedido anula vantagens não usufruídas.',
 'Será convertido em valor equivalente a 6 (seis) remunerações vigentes na data do pagamento a título de indenização.',
 'O Estado depositará no FGTS do servidor.',
 'Será averbado no seu novo cargo do Judiciário para somar na sua aposentadoria civil futura.',
 'Será convertido em 3 remunerações, pagando-se apenas o último quinquênio.',
 'B',
 'A Licença Especial não gozada, se o militar for licenciado a pedido, será convertida em valor equivalente a 1 remuneração para cada mês a que possuir direito (2 quinquênios = 6 meses = 6 remunerações).',
 'Art. 78, §8º, LC 194/2012',
 'dificil'),

-- Q29: Sindicância
(@cat_p3,
 'O Capitão Comandante da Companhia percebe que um computador do quartel sumiu. Ele instaura uma Sindicância Inquisitorial para apurar a materialidade antes de abrir PAD. Segundo o CEDM/RR, o rito e formalidades dessa Sindicância são baseados em quais critérios?',
 'Rigorismo formal, amplitude de defesa obrigatória no início e citação em Diário Oficial.',
 'Código de Processo Penal Militar na íntegra.',
 'Conselho de Disciplina.',
 'Critérios de simplicidade, celeridade e informalismo moderado, visando apenas elucidar as circunstâncias, ainda que oportunizado o contraditório.',
 'Procedimento sumário presidido unicamente por juiz de direito.',
 'D',
 'A Sindicância Inquisitorial foca na investigação (Art. 96, I), devendo ser orientada pelos critérios da simplicidade, celeridade e informalismo moderado, para embasar um futuro PAD ou arquivamento.',
 'Art. 96, I, Lei nº 963/2014',
 'dificil'),

-- Q30: Ingresso no QEO (Requisito Especial)
(@cat_p3,
 'O Subtenente QEP Gomes cumpriu 19 anos de efetivo serviço e é o mais antigo para ascender ao QEO PM/BM. Ele possui comportamento "Ótimo". Além da antiguidade, tempo e comportamento, qual requisito essencial deve ser exigido no ato da matrícula do CHO?',
 'Carteira Nacional de Habilitação Categoria "D".',
 'Comprovação de Curso de Aperfeiçoamento de Sargentos (CAS).',
 'Comprovação de Curso Superior reconhecido ou autorizado pelo Ministério da Educação.',
 'Idade máxima de 45 anos.',
 'Indicação direta e secreta do Comandante-Geral.',
 'C',
 'O Art. 22, §17 do Estatuto exige categoricamente que, no ato da matrícula do CHO, o Subtenente comprove ser portador de diploma de Curso Superior.',
 'Art. 22, §17, LC 194/2012',
 'dificil'),

-- Q31: Agravantes na Dosimetria
(@cat_p3,
 'O Soldado Roberto falsificou deliberadamente a assinatura do seu superior para se escalonar em serviço voluntário remunerado. A fraude foi descoberta. O Comandante enquadrou como infração Grave e detectou que a atitude teve "o fim de obstruir ou dificultar a apuração administrativa e acobertar erro próprio" (Art. 39). Qual regra obrigatória de dosimetria o Comandante aplicará?',
 'A punição deverá ser aplicada do limite mínimo à metade da pena máxima.',
 'A punição será aplicada obrigatoriamente em demissão, por se tratar de crime.',
 'A punição será aplicada da metade ao limite máximo de dias estabelecidos (até 30 dias de permanência ou até 10 dias de detenção).',
 'A punição será fixada na metade, sem possibilidade de aumento.',
 'Fica a livre critério do Comandante fixar entre 1 e 30 dias de prisão fechada.',
 'C',
 'Quando as circunstâncias agravantes preponderarem, o CEDM (Art. 53, §3º) determina que a punição seja aplicada "da metade ao limite máximo de dias estabelecidos".',
 'Arts. 39, XII e XIII e 53, §3º, Lei nº 963/2014',
 'dificil'),

-- Q32: Trânsito e Instalação
(@cat_p3,
 'O 2º Tenente PM Costa foi transferido, por necessidade do serviço, de Boa Vista para Pacaraima, exigindo mudança obrigatória com sua família. O Comando determinou apresentação imediata em 2 dias. A ordem feriu direitos estatutários de afastamento do Tenente Costa? Quais são os prazos de Trânsito e Instalação?',
 'Sim. Ele tem direito a até 10 dias de Trânsito e mais 20 dias de Instalação.',
 'Não, transferências ex-officio não geram direito a afastamento prévio.',
 'Sim. A lei garante até 20 dias de Trânsito (preparativos) e até 10 dias de Instalação na chegada.',
 'Sim. O prazo único consolidado é de 30 dias úteis de luto/trânsito.',
 'Não. A distância até Pacaraima não gera pagamento de folgas.',
 'C',
 'O militar tem direito a até 20 dias para o Trânsito (viagem/mudança) e até 10 dias para a Instalação (se acomodar na nova sede).',
 'Art. 75, III e IV, LC 194/2012',
 'dificil'),

-- Q33: Recusa de Cumprimento de Sanção
(@cat_p3,
 'O Soldado Tiago discorda da Permanência Disciplinar de 5 dias que recebeu. Ele chega no quartel no dia do início da punição, assina a notificação e diz ao Oficial de Dia: "Não vou ficar no quartel, estou indo para casa". Qual infração grave e imediata o Soldado comete?',
 'Transgressão média de desobediência a rotina.',
 'Transgressão grave tipificada como: "deixar de cumprir punição legalmente imposta".',
 'Crime militar de Insubordinação (sem repercussão administrativa).',
 'Infração de trânsito.',
 'Abandono de Posto, passível de demissão direta sem PAD.',
 'B',
 'Recusar-se a cumprir a punição após a publicação oficial é Transgressão Grave, expressa no inciso XXX do Art. 40.',
 'Art. 40, §3º, XXX, Lei nº 963/2014',
 'dificil'),

-- Q34: Casamento entre Militares
(@cat_p3,
 'O Tenente QOC Pedro e a Sargento QPC Joana são casados. Pedro é transferido, por necessidade do serviço, de Boa Vista para Caracaraí. Joana quer ser transferida com o marido. O que a Sargento Joana pode pleitear à administração e com qual fundamento?',
 'Apenas Licença sem remuneração por 2 anos.',
 'Transferência compulsória por interesse do serviço.',
 'Transferência para Caracaraí, por "interesse próprio", com base na garantia legal de acompanhar cônjuge transferido por necessidade do serviço.',
 'Transferência por permuta obrigatória.',
 'Desligamento do QPC para ingresso na reserva com proventos proporcionais.',
 'C',
 'O Estatuto (Art. 59, III, "l") garante o direito do militar de ser transferido, por interesse próprio, para a mesma localidade onde o cônjuge militar tenha sido transferido por ordem do Estado.',
 'Art. 59, III, "l", LC 194/2012',
 'dificil'),

-- Q35: Indenização de Formação/Curso
(@cat_p3,
 'O Capitão Mário realizou um Curso de Especialização Tática em Israel, custeado 100% pelo Estado de Roraima (8 meses, terminando em janeiro de 2025). Em dezembro de 2025 (11 meses após voltar), ele pede exoneração para morar no exterior. O Governo pode cobrar os custos do curso?',
 'Sim, mediante indenização de todas as despesas decorrentes com a realização do referido curso, pois não decorreram 24 meses do seu término.',
 'Não, pois o treinamento incorpora-se ao currículo do militar e o Estado assume o risco do investimento.',
 'Sim, porém limitado a 50% dos gastos.',
 'Não, pois cursos fora do Brasil não estão abarcados pelo Estatuto de Roraima.',
 'Sim, mas apenas o custo das passagens aéreas e diárias.',
 'A',
 'O Estatuto prevê que o militar que se licenciar antes de 24 meses do término de curso custeado pelo Estado deverá indenizar todas as despesas decorrentes da realização do referido curso.',
 'LC 194/2012',
 'dificil'),

-- Q36: Transgressão na Mídia Social
(@cat_p3,
 'O Cabo J. Rodrigues criou um perfil anônimo no Instagram e fez montagens em vídeo utilizando fotos com o rosto do Comandante do Batalhão, contendo ofensas pesadas e cenas humilhantes que mancham o nome da instituição. Em quais tipificações disciplinares graves o Cabo incidiu?',
 'Publicar assuntos sem autorização da SECOM (falta média) e esquivar-se ao cumprimento de ordem moral (média).',
 'Exercício irregular de publicidade, e infração contra direitos autorais.',
 'Utilizar-se do anonimato para fins ilícitos, e efetuar a produção/divulgação digital de cenas atentatórias à dignidade de membros da Corporação (infrações graves).',
 'Acesso indevido à intranet, apenas (infração leve).',
 'Insubordinação digital (infração média).',
 'C',
 'O CEDM tipifica como infrações graves: utilizar-se do anonimato para fins ilícitos e efetuar produção/divulgação digital de cenas atentatórias à dignidade de membros da Corporação.',
 'Lei nº 963/2014',
 'dificil'),

-- Q37: Promoção Post-Mortem
(@cat_p3,
 'O Soldado Freitas foi morto em combate (preservação da ordem pública) durante confronto com uma facção criminosa, agindo heroicamente. Quais os efeitos da promoção post-mortem e de qual graduação a família receberá a pensão?',
 'O Estado concede um título de Honra ao Mérito, mas a pensão é baseada no salário de Soldado.',
 'Ele não recebe promoção post-mortem porque o combate não foi declarado guerra.',
 'A promoção post-mortem ocorrerá para Cabo (posto imediatamente superior), visando expressar reconhecimento do Estado, e a pensão deixada aos beneficiários corresponderá aos vencimentos integrais dessa nova graduação.',
 'A família receberá indenização, sem elevação do posto.',
 'A promoção post-mortem o eleva diretamente a 3º Sargento.',
 'C',
 'A promoção post-mortem eleva ao posto/graduação imediatamente superior (Soldado → Cabo), expressando reconhecimento do Estado. A pensão aos beneficiários corresponde aos vencimentos integrais da nova graduação.',
 'LC 194/2012',
 'dificil'),

-- Q38: Prescrição Executória da Punição
(@cat_p3,
 'O Conselho de Disciplina do Sargento Souza foi concluído. O Governador assinou a sanção de 15 dias de Detenção, publicada no Diário Oficial. O escalão inferior esqueceu de notificar o Sargento para cumprimento. Passou-se 1 ano e 3 meses da solução definitiva. O Comandante pode determinar o cumprimento agora?',
 'Sim, pois crimes e faltas graves não prescrevem sua execução.',
 'Sim, o Estado tem 5 anos para executar uma sanção disciplinar após o trânsito em julgado.',
 'Não, prescreveu. O direito de punir (aplicar/executar a sanção) prescreve em 01 (um) ano após a solução definitiva se ela não for aplicada.',
 'Não, pois a pena máxima é 30 dias e ele excedeu esse prazo de esquecimento.',
 'Sim, descontando os finais de semana.',
 'C',
 'O Art. 97, III do CEDM/RR prevê que o direito de punir prescreve em 01 ano após a solução definitiva se não for executada a sanção.',
 'Art. 97, III, Lei nº 963/2014',
 'dificil'),

-- Q39: Remuneração e Cargo Civil (Saúde)
(@cat_p3,
 'A Capitão QOS (Médica da Corporação) Juliana passou em concurso para ser médica concursada de um município à tarde, cumprindo seu expediente militar pela manhã. É permitida a acumulação desses dois cargos e das remunerações?',
 'Não, militares em atividade não podem ter vínculo civil algum, sendo obrigados a escolher um.',
 'Sim, o Estatuto permite aos oficiais (com formação científica em saúde) a acumulação lícita do cargo de militar estadual com outro cargo de provimento efetivo, nas áreas de saúde, desde que haja compatibilidade de horários.',
 'Sim, porém recebendo apenas um dos subsídios (o maior).',
 'Não, a acumulação aplica-se apenas a militares da reserva (aposentados).',
 'Sim, desde que se limite à carga horária total semanal de 24 horas.',
 'B',
 'O Estatuto permite aos oficiais com formação científica em saúde a acumulação lícita do cargo militar estadual com outro cargo de provimento efetivo na área de saúde, desde que haja compatibilidade de horários.',
 'LC 194/2012',
 'dificil'),

-- Q40: Transgressão de Trânsito
(@cat_p3,
 'O Soldado Roberto, durante patrulhamento ostensivo de rotina e sem atender a qualquer ocorrência de emergência, avança deliberadamente um sinal vermelho e bate a viatura em um carro de passeio, tudo comprovado por câmeras. No âmbito disciplinar interno, Roberto cometeu transgressão tipificada no CEDM/RR? Qual a classificação?',
 'Sim, conduzir viatura com imprudência/negligência e desrespeitar regras de trânsito constituem infrações de natureza Média.',
 'Não, infrações de trânsito não são regidas pelo CEDM.',
 'Sim, mas como o veículo era do Estado, o dano atrai demissão automática.',
 'Sim, infração Leve, que resulta em 2 dias de retenção no alojamento.',
 'Sim, infração Grave ("crime e transgressão"), devendo passar por Conselho de Disciplina.',
 'A',
 'Conduzir viatura com imprudência/negligência e desrespeitar regras de trânsito (avanço de sinal) constituem infrações de natureza Média no CEDM/RR.',
 'Lei nº 963/2014',
 'dificil');

SET foreign_key_checks = 1;
