-- ============================================================
-- PROVA 2 — 80 Questões de Nível DIFÍCIL
-- Estatuto dos Militares (LC nº 194/2012) + CEDM/RR (Lei nº 963/2014) + LC nº 372/2026
-- Todas as questões: nível "dificil"
-- ============================================================
SET NAMES utf8mb4;
SET foreign_key_checks = 0;

-- Criar categoria Prova 2
INSERT IGNORE INTO categorias (nome, descricao)
VALUES ('🎯 Prova 2', 'Questões Nível DIFÍCIL — Estatuto (LC 194/2012), CEDM/RR (Lei 963/2014) e LC 372/2026');

SET @cat_p2 = (SELECT id FROM categorias WHERE nome = '🎯 Prova 2' LIMIT 1);

INSERT INTO questoes
    (categoria_id, enunciado, opcao_a, opcao_b, opcao_c, opcao_d, opcao_e,
     resposta_correta, explicacao, referencia_legal, nivel)
VALUES

-- ====== BLOCO 1: PROMOÇÕES (LC 194/2012, arts. 71-99) ======

(@cat_p2,
 'Segundo a LC nº 194/2012, a promoção do militar estadual é ato administrativo e tem como finalidade básica:',
 'Premiar o militar com melhor avaliação de desempenho anual.',
 'O preenchimento seletivo de vagas, graduar hierarquicamente o acesso na carreira e incrementar a eficiência da corporação.',
 'Atender exclusivamente ao critério de antiguidade para todos os postos e graduações.',
 'Garantir a isonomia remuneratória entre os quadros de oficiais e praças.',
 'Promover automaticamente o militar após cumprimento do interstício mínimo.',
 'B',
 'A promoção visa preencher seletivamente vagas, graduar o acesso na carreira e incrementar a eficiência institucional, conforme os princípios do Estatuto.',
 'Art. 71, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'O Estatuto prevê que a promoção pode ocorrer por determinados critérios. Qual alternativa lista CORRETAMENTE critérios de promoção previstos no art. 73?',
 'Antiguidade, merecimento e bravura, exclusivamente.',
 'Antiguidade, merecimento, bravura e post-mortem, apenas.',
 'Antiguidade, merecimento, ato de bravura, post-mortem, tempo de contribuição, tempo de efetivo serviço, mérito intelectual, ressarcimento de preterição e tempo de convocação.',
 'Antiguidade, merecimento, bravura, post-mortem e ressarcimento de preterição, apenas.',
 'Antiguidade e merecimento exclusivamente.',
 'C',
 'O art. 73 (com alterações das LCs 260/2017, 308/2022 e 322/2022) prevê nove critérios de promoção: antiguidade, merecimento, ato de bravura, post-mortem, tempo de contribuição, tempo de efetivo serviço, mérito intelectual, ressarcimento de preterição e tempo de convocação.',
 'Art. 73, incisos I a IX, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'Sobre a promoção por antiguidade, qual condição pode impedir o militar mais antigo de ser promovido, mesmo tendo cumprido o interstício?',
 'Estar em gozo de licença-prêmio.',
 'Estar agregado por motivo de saúde há menos de um ano.',
 'Estar submetido a Conselho de Justificação ou Conselho de Disciplina, ou preso preventivamente.',
 'Ter sido punido com advertência nos últimos seis meses.',
 'Estar em exercício de função de natureza policial militar em outro estado.',
 'C',
 'O militar submetido a Conselho de Justificação/Disciplina ou preso preventivamente tem sua promoção por antiguidade impedida até solução definitiva.',
 'Art. 78, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'A promoção post-mortem é efetivada a contar de qual data?',
 'Da data da publicação do ato no Diário Oficial.',
 'Da data do falecimento do militar.',
 'Da data do requerimento dos herdeiros.',
 'Do primeiro dia do mês subsequente ao falecimento.',
 'Da data da conclusão do inquérito sobre as circunstâncias do óbito.',
 'B',
 'A promoção post-mortem retroage à data do falecimento do militar, produzindo efeitos patrimoniais para os herdeiros.',
 'Art. 73, IV, LC nº 194/2012 (redação LC nº 308/2022)',
 'dificil'),

(@cat_p2,
 'Na promoção por merecimento, qual é o papel da Comissão de Promoção de Oficiais (CPO) ou da Comissão de Promoção de Praças (CPP)?',
 'Apenas homologar a lista de antiguidade sem poder de alteração.',
 'Elaborar o Quadro de Acesso por Merecimento (QAM), avaliando os aspectos de desempenho profissional, conceito e aptidão dos candidatos.',
 'Decidir de forma vinculante, sem participação do Comandante-Geral.',
 'Aplicar exclusivamente critérios objetivos de tempo de serviço.',
 'Funcionar apenas em caso de empate entre candidatos na lista de antiguidade.',
 'B',
 'As Comissões de Promoção elaboram o QAM com base em critérios de desempenho, conceito e aptidão, subsidiando a decisão sobre promoção por merecimento.',
 'Art. 88, LC nº 194/2012',
 'dificil'),

-- ====== BLOCO 2: REFORMA E RESERVA (LC 194/2012, arts. 100-118) ======

(@cat_p2,
 'A transferência para a reserva remunerada ex-officio do oficial ocorre, entre outras hipóteses, quando este atingir qual idade-limite?',
 '55 anos para todos os postos.',
 '60 anos para Coronel, 58 para Tenente-Coronel, 56 para Major e 54 para Capitão.',
 'A idade-limite fixada em lei para o posto que ocupa.',
 '65 anos independentemente do posto.',
 '50 anos para praças e 60 anos para oficiais.',
 'C',
 'Conforme art. 115-B (redação LC 308/2022), a transferência para reserva remunerada de ofício ocorre quando o militar for enquadrado nos requisitos da Lei do Sistema de Proteção Social dos Militares de Roraima.',
 'Art. 115-B, LC nº 194/2012 (redação LC nº 308/2022)',
 'dificil'),

(@cat_p2,
 'A reforma ex-officio do militar por incapacidade definitiva pode decorrer de acidente ou doença. Quando a incapacidade decorrer de acidente em serviço ou moléstia adquirida em função dele, qual é a consequência remuneratória?',
 'O militar reformado percebe proventos proporcionais ao tempo de contribuição.',
 'O militar reformado faz jus a proventos correspondentes ao grau hierárquico imediatamente superior ao que possuía.',
 'O militar reformado perde direito a remuneração, recebendo apenas pensão.',
 'O militar reformado percebe exclusivamente os proventos do posto/graduação que possuía.',
 'O militar reformado é indenizado em parcela única equivalente a cinco anos de subsídio.',
 'B',
 'Conforme arts. 119 e 120 (redação LC 260/2017), quando a incapacidade decorrer de acidente em serviço ou moléstia profissional, o reformado faz jus a proventos correspondentes ao grau hierárquico imediatamente superior.',
 'Arts. 119 e 120, LC nº 194/2012 (redação LC nº 260/2017)',
 'dificil'),

(@cat_p2,
 'O militar da reserva remunerada pode ser convocado ao serviço ativo. Nessa situação, em relação à contagem de tempo de serviço, como é computado o período de convocação?',
 'Não é computado para qualquer efeito.',
 'É computado apenas para fins de aposentadoria.',
 'É computado como tempo de efetivo serviço militar estadual.',
 'É computado pela metade.',
 'É computado como tempo de serviço civil.',
 'C',
 'O período de convocação do militar da reserva é computado integralmente como tempo de efetivo serviço militar estadual.',
 'LC nº 194/2012, convocação da reserva',
 'dificil'),

(@cat_p2,
 'Para a transferência para a reserva remunerada a pedido, o militar deve cumprir qual requisito mínimo de tempo de serviço, segundo o Estatuto?',
 '25 anos de efetivo serviço.',
 '30 anos de contribuição.',
 '20 anos de efetivo serviço.',
 '15 anos de efetivo serviço mais idade mínima de 50 anos.',
 'O tempo mínimo fixado em lei para o respectivo posto ou graduação.',
 'E',
 'A reserva a pedido exige o cumprimento do tempo mínimo de serviço previsto em lei para o posto ou graduação do militar.',
 'LC nº 194/2012, reserva a pedido',
 'dificil'),

(@cat_p2,
 'O oficial reformado por incapacidade definitiva que vier a ser julgado apto em inspeção de saúde posterior poderá retornar ao serviço ativo?',
 'Sim, automaticamente, desde que haja vaga.',
 'Não, a reforma é irreversível em qualquer hipótese.',
 'Sim, desde que cessados os motivos que ensejaram a reforma, com observância do prazo-limite para permanência no serviço ativo.',
 'Sim, mas apenas para a reserva remunerada, nunca para o serviço ativo.',
 'Somente por decisão judicial, nunca por via administrativa.',
 'C',
 'Conforme o art. 122 e seu parágrafo único, o militar reformado por incapacidade que for julgado apto poderá retornar ao serviço ativo, desde que cessados os motivos da reforma e observado o prazo-limite para permanência no serviço ativo.',
 'Art. 122, parágrafo único, LC nº 194/2012',
 'dificil'),

-- ====== BLOCO 3: REMUNERAÇÃO E VANTAGENS (LC 194/2012, arts. 43-70) ======

(@cat_p2,
 'Sobre a remuneração do militar estadual de Roraima, qual alternativa está CORRETA segundo o art. 63 do Estatuto (LC nº 194/2012, com redação da LC nº 260/2017)?',
 'Subsídio fixado em parcela única, não excluindo o percebimento de indenizações e vantagens eventuais previstas em lei.',
 'Soldo, gratificações, adicionais e indenizações, na forma prevista em lei.',
 'Vencimento básico e representação, nos moldes do serviço público civil.',
 'Soldo e auxílio-moradia exclusivamente.',
 'Soldo e adicional de insalubridade, sem outras verbas.',
 'A',
 'Conforme art. 63 (redação da LC 260/2017), os militares são remunerados exclusivamente por subsídio fixado em parcela única. O §2º esclarece que o subsídio não exclui o percebimento de direitos, indenizações e vantagens eventuais previstos em lei.',
 'Art. 63, caput e §2º, LC nº 194/2012 (redação da LC nº 260/2017)',
 'dificil'),

(@cat_p2,
 'Com a adoção do subsídio como forma de remuneração (art. 63, LC nº 194/2012, redação da LC nº 260/2017), qual afirmação é CORRETA sobre a estrutura remuneratória do militar estadual?',
 'O subsídio é fixado em parcela única, devendo ser observados percentuais de escalonamento vertical e horizontal entre os postos e graduações, tomando como parâmetro o maior subsídio do posto de Coronel.',
 'O subsídio é composto por soldo base mais gratificações variáveis.',
 'O subsídio pode ser fracionado em parcelas mensais diferenciadas.',
 'O subsídio não admite qualquer outra verba, nem mesmo de natureza indenizatória.',
 'O subsídio é igual para todos os postos e graduações.',
 'A',
 'Conforme art. 63, §1º (redação da LC 260/2017), devem ser observados percentuais de escalonamento vertical e horizontal entre os postos e graduações, tendo como parâmetro o maior subsídio do posto de Coronel.',
 'Art. 63, §1º, LC nº 194/2012 (redação da LC nº 260/2017)',
 'dificil'),

(@cat_p2,
 'O art. 59, inciso XVIII, do Estatuto (com redação da LC nº 260/2017) prevê indenização de interiorização. A quem ela é devida?',
 'A qualquer militar que resida fora da capital.',
 'Aos militares do Estado e aos integrantes do Quadro dos Policiais Militares do Ex-Território Federal de Roraima lotados em Unidades Militares fora do município de Boa Vista.',
 'Apenas aos oficiais superiores em missão no interior.',
 'Somente aos militares em operação de fronteira por tempo superior a 30 dias.',
 'A todos os militares, independentemente da lotação.',
 'B',
 'Conforme art. 59, XVIII (redação da LC 260/2017), a indenização de interiorização é devida aos militares estaduais e aos do Quadro do Ex-Território que, por necessidade do serviço, estão lotados em Unidades Militares fora de Boa Vista.',
 'Art. 59, XVIII, LC nº 194/2012 (redação da LC nº 260/2017)',
 'dificil'),

-- ====== BLOCO 4: TRANSGRESSÕES DISCIPLINARES (CEDM/RR, arts. 23-42) ======

(@cat_p2,
 'O CEDM/RR classifica as transgressões disciplinares em três naturezas. Qual alternativa apresenta corretamente essa classificação e o critério de gravidade?',
 'Faltas leves, médias e graves, classificadas pelo dano causado ao serviço.',
 'Transgressões leves, médias e graves, classificadas segundo a maior ou menor gravidade do ato praticado e suas circunstâncias.',
 'Infrações administrativas simples, qualificadas e gravíssimas.',
 'Transgressões disciplinares de 1º, 2º e 3º grau.',
 'Desvios de conduta menores, intermediários e capitais.',
 'B',
 'O CEDM classifica as transgressões em leves, médias e graves, conforme a gravidade do ato e suas circunstâncias.',
 'Art. 23, caput, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'São circunstâncias atenuantes da transgressão disciplinar previstas no CEDM/RR, EXCETO:',
 'Bom comportamento.',
 'Ter cometido a transgressão para evitar mal maior.',
 'Relevância de serviços prestados anteriormente.',
 'Ter sido coagido a praticar a transgressão por superior hierárquico.',
 'Ter confessado a autoria antes de qualquer procedimento investigatório.',
 'D',
 'A coação por superior hierárquico pode ser excludente ou atenuante especial, mas no rol típico de atenuantes estão: bom comportamento, evitar mal maior, relevância de serviços prestados e confissão espontânea.',
 'Art. 28, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'A prescrição da punibilidade da transgressão disciplinar no CEDM/RR ocorre em qual prazo, contado de quando?',
 '2 anos, contados da data do conhecimento do fato pela autoridade competente.',
 '5 anos, contados da data do fato.',
 '1 ano, contados da data da instauração do procedimento.',
 '3 anos, contados da data da publicação da portaria instauradora.',
 '6 meses, contados da data da sindicância.',
 'B',
 'A prescrição da punibilidade da transgressão disciplinar ocorre em 5 anos contados da data do fato.',
 'Art. 35, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'Segundo o CEDM/RR, quando a transgressão disciplinar também constituir crime militar, qual procedimento deve ser adotado?',
 'Aplica-se somente a punição disciplinar, ficando prejudicada a ação penal.',
 'O procedimento disciplinar deve aguardar o trânsito em julgado da ação penal militar.',
 'A transgressão disciplinar residual será apurada independentemente da ação penal militar, sem prejuízo desta.',
 'O militar fica isento de punição disciplinar se absolvido na ação penal.',
 'O Comandante-Geral decide se instaura procedimento disciplinar ou encaminha ao juízo militar.',
 'C',
 'O procedimento disciplinar é independente da ação penal militar, sendo apurada a transgressão disciplinar residual sem prejuízo do processo criminal.',
 'Art. 24, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'Dentre as transgressões disciplinares GRAVES previstas no CEDM/RR, qual das seguintes NÃO se enquadra nessa classificação?',
 'Publicar, sem autorização, documentos oficiais ou assuntos de caráter reservado.',
 'Chegar atrasado ao serviço sem justificativa, por uma única vez.',
 'Embriagar-se em serviço ou apresentar-se embriagado para o serviço.',
 'Praticar ato que importe em escândalo ou que comprometa a dignidade da função militar.',
 'Abandonar o serviço para o qual tenha sido designado.',
 'B',
 'Atraso isolado ao serviço é transgressão leve; as demais alternativas descrevem condutas graves.',
 'Art. 23, §5º, Anexo I, Lei nº 963/2014',
 'dificil'),

-- ====== BLOCO 5: PUNIÇÕES DISCIPLINARES (CEDM/RR, arts. 43-79) ======

(@cat_p2,
 'O CEDM/RR prevê as seguintes punições disciplinares em ordem crescente de gravidade:',
 'Advertência, repreensão, permanência disciplinar, detenção disciplinar e licenciamento ou exclusão a bem da disciplina.',
 'Repreensão, advertência, suspensão, prisão e demissão.',
 'Advertência, suspensão, transferência compulsória e exclusão.',
 'Repreensão, detenção, prisão, reforma disciplinar e exclusão.',
 'Advertência, repreensão, prisão disciplinar, reforma e demissão.',
 'A',
 'As punições escalonadas em gravidade são: advertência, repreensão, permanência disciplinar, detenção disciplinar e licenciamento/exclusão a bem da disciplina. O CEDM/RR NÃO prevê "prisão disciplinar" como punição.',
 'Lei nº 963/2014 (CEDM/RR)',
 'dificil'),

(@cat_p2,
 'Qual a diferença entre a permanência disciplinar e a detenção disciplinar no CEDM/RR?',
 'São sinônimos usados para a mesma punição.',
 'A permanência disciplinar mantém o militar na unidade sem confinamento; a detenção disciplinar implica retenção sem participação em serviços.',
 'A permanência é aplicada apenas a oficiais; a detenção, apenas a praças.',
 'A permanência é medida judicial; a detenção é administrativa.',
 'Ambas exigem autorização do Governador do Estado.',
 'B',
 'A permanência disciplinar mantém o militar na unidade sem confinamento, enquanto a detenção disciplinar implica retenção sem participação em serviços. São punições distintas em gravidade.',
 'Lei nº 963/2014 (CEDM/RR)',
 'dificil'),

(@cat_p2,
 'O Comandante de Pelotão tem competência para aplicar quais punições disciplinares, segundo o CEDM/RR?',
 'Advertência, repreensão, permanência disciplinar e detenção disciplinar.',
 'Apenas advertência e repreensão.',
 'Advertência, repreensão e permanência disciplinar (até 10 dias para praças e até 5 dias para oficiais).',
 'Todas as punições previstas no Código, sem limitação.',
 'Apenas permanência disciplinar de até 5 dias para todos os militares.',
 'C',
 'O Comandante de Pelotão tem competência limitada: pode aplicar advertência, repreensão e permanência disciplinar (até 10 dias para praças, até 5 dias para oficiais). Ele NÃO pode aplicar detenção disciplinar.',
 'Lei nº 963/2014 (CEDM/RR)',
 'dificil'),

(@cat_p2,
 'Um Comandante de Pelotão deseja aplicar 20 dias de punição restritiva de liberdade a um Cabo. Ele tem competência para isso?',
 'Sim, pois o Comandante de Pelotão pode aplicar qualquer punição a praças.',
 'Sim, desde que autorizado pelo Comandante de Companhia.',
 'Não, pois o Comandante de Pelotão só pode aplicar permanência disciplinar de até 10 dias para praças, e não possui competência para aplicar detenção disciplinar.',
 'Sim, desde que a punição seja convertida em detenção.',
 'Não, pois a punição máxima é de 15 dias para qualquer autoridade.',
 'C',
 'O Comandante de Pelotão só pode aplicar permanência disciplinar de até 10 dias para praças. Ele excede tanto o prazo (20 > 10) quanto sua competência (não pode aplicar detenção). A aplicação de detenção disciplinar é competência de autoridade superior.',
 'Lei nº 963/2014 (CEDM/RR)',
 'dificil'),

(@cat_p2,
 'O cancelamento de punição disciplinar no CEDM/RR pode ocorrer após quanto tempo sem nova punição e sob qual condição?',
 '1 ano sem punição, automaticamente.',
 '2 anos sem nova punição de qualquer natureza, mediante requerimento do militar e decisão da autoridade competente.',
 '5 anos sem punição, independentemente de requerimento.',
 '3 anos sem punição grave, por decisão do Comandante-Geral.',
 '6 meses sem advertência, de ofício.',
 'B',
 'O cancelamento de punição ocorre após 2 anos sem nova punição, mediante requerimento e decisão da autoridade.',
 'Art. 74, Lei nº 963/2014',
 'dificil'),

-- ====== BLOCO 6: SINDICÂNCIAS E PROCEDIMENTOS (CEDM/RR, arts. 96-102) ======

(@cat_p2,
 'O CEDM/RR prevê três tipos de sindicância. Qual alternativa descreve corretamente a Sindicância Sumária?',
 'Tem cunho investigativo para verificar materialidade e indício de autoria.',
 'Apura transgressão disciplinar com autoria e materialidade já estabelecidas, instruída de forma simplificada e com prazo reduzido.',
 'É a sindicância mais ampla, com todas as garantias do contraditório e da ampla defesa.',
 'É instaurada exclusivamente pelo Comandante-Geral para casos graves.',
 'Substitui o Processo Administrativo Disciplinar para transgressões leves.',
 'B',
 'A Sindicância Sumária apura transgressão com autoria e materialidade já conhecidas, de forma simplificada e prazo mais curto.',
 'Art. 96, II, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'A Sindicância Regular, conforme o CEDM/RR, é instaurada quando:',
 'A materialidade é conhecida, mas a autoria não está claramente identificada.',
 'A transgressão e a autoria são conhecidas e comprovadas.',
 'Há necessidade de investigação preliminar antes de qualquer medida.',
 'Os fatos exigem apuração ampla com instrução completa, contraditório e ampla defesa.',
 'O militar já foi punido e recorre da decisão.',
 'D',
 'A Sindicância Regular é o procedimento mais amplo, com instrução completa e garantias do contraditório e ampla defesa.',
 'Art. 96, III, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'O prazo para conclusão da sindicância inquisitorial é de quantos dias, prorrogável por mais quantos?',
 '30 dias, prorrogável por mais 30.',
 '20 dias, prorrogável por mais 20.',
 '15 dias, prorrogável por mais 15.',
 '10 dias, improrrogável.',
 '60 dias, prorrogável por mais 30.',
 'B',
 'A sindicância inquisitorial deve ser concluída em 20 dias, prorrogáveis por mais 20.',
 'Art. 97, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'Qual é o prazo para conclusão da sindicância sumária e da sindicância regular, respectivamente?',
 'Sumária: 10 dias + 10; Regular: 30 dias + 20.',
 'Sumária: 15 dias + 15; Regular: 40 dias + 20.',
 'Sumária: 30 dias + 30; Regular: 60 dias + 30.',
 'Sumária: 5 dias + 5; Regular: 20 dias + 20.',
 'Sumária: 20 dias + 20; Regular: 30 dias + 30.',
 'B',
 'A sindicância sumária tem prazo de 15 dias (prorrogáveis por mais 15) e a regular tem prazo de 40 dias (prorrogáveis por mais 20).',
 'Arts. 98 e 99, Lei nº 963/2014',
 'dificil'),

-- ====== BLOCO 7: RECURSOS DISCIPLINARES (CEDM/RR, arts. 89-95) ======

(@cat_p2,
 'O militar punido pode interpor recurso disciplinar em qual prazo, contado de quando?',
 '5 dias úteis, contados da publicação da punição em Boletim Interno.',
 '10 dias corridos, contados da ciência da punição.',
 '3 dias úteis, contados da notificação pessoal.',
 '15 dias corridos, contados da publicação no Diário Oficial.',
 '48 horas, contadas da aplicação da punição.',
 'A',
 'O prazo recursal é de 5 dias úteis, contados da publicação da punição em Boletim Interno.',
 'Art. 85, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'A quem deve ser dirigido o recurso disciplinar e qual é o efeito da sua interposição sobre a punição?',
 'Ao Governador do Estado; o recurso suspende automaticamente a punição.',
 'Ao Secretário de Segurança Pública; sem efeito suspensivo.',
 'À autoridade imediatamente superior à que aplicou a punição; o recurso não possui efeito suspensivo, salvo decisão expressa.',
 'Ao Tribunal de Justiça Militar; com efeito suspensivo obrigatório.',
 'Ao próprio Comandante que aplicou a punição; com efeito devolutivo e suspensivo.',
 'C',
 'O recurso é dirigido à autoridade superior àquela que aplicou a punição e, via de regra, não tem efeito suspensivo.',
 'Art. 86, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'No âmbito do recurso disciplinar, a autoridade que aplicou a sanção tem o prazo de 5 dias úteis para reconsiderar. Se não reconsiderar, deve:',
 'Manter a punição silenciosamente, sem encaminhamento.',
 'Encaminhar o recurso à autoridade destinatária com despacho fundamentado, juntando documentação necessária.',
 'Determinar nova sindicância para reavaliar o caso.',
 'Submeter o caso ao Conselho de Disciplina.',
 'Arquivar o recurso automaticamente.',
 'B',
 'Se não reconsiderar em 5 dias úteis, encaminha o recurso à autoridade superior com despacho fundamentado e documentação.',
 'Art. 85, parágrafo único, Lei nº 963/2014',
 'dificil'),

-- ====== BLOCO 8: LICENÇAS E AFASTAMENTOS (LC 194/2012, arts. 119-130) ======

(@cat_p2,
 'A licença para tratar de interesse particular pode ser concedida ao militar estadual por qual prazo máximo?',
 '6 meses, improrrogável.',
 'Até 2 anos de afastamento.',
 'Até 3 anos, podendo ser fracionada.',
 '1 ano, prorrogável por mais 1 ano.',
 'Prazo indeterminado, a critério do Comandante-Geral.',
 'B',
 'Conforme art. 79 (redação LC 260/2017), a licença para tratar de interesse particular não pode exceder 02 (dois) anos de afastamento.',
 'Art. 79, LC nº 194/2012 (redação LC nº 260/2017)',
 'dificil'),

(@cat_p2,
 'Durante a licença para tratar de interesse particular, o militar estadual:',
 'Percebe remuneração integral.',
 'Percebe metade do soldo.',
 'Não percebe remuneração, e o período não é computado como tempo de serviço.',
 'Percebe apenas auxílio-alimentação.',
 'Percebe remuneração integral nos primeiros 6 meses e sem remuneração depois.',
 'C',
 'A licença para tratar de interesse particular é sem remuneração e o período não conta como tempo de serviço.',
 'Art. 119, §§, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'A licença para acompanhar cônjuge ou companheiro deslocado para cursos de interesse das instituições é concedida SEM prejuízo da remuneração. Qual é o prazo para cursos com duração superior a dois anos?',
 '30 dias.',
 '60 dias.',
 '90 dias.',
 '120 dias.',
 'Pelo tempo que durar o curso integralmente.',
 'C',
 'Conforme art. 88, III, para cursos com duração superior a dois anos, a licença para acompanhar cônjuge é de 90 dias, sem prejuízo da remuneração.',
 'Art. 88, III, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'O militar que se afastar para frequentar curso no exterior por conta do Estado tem qual obrigação ao retorno?',
 'Permanecer por 5 anos na corporação.',
 'Permanecer no exercício das funções por período igual ao do afastamento concedido, sob pena de ressarcimento proporcional.',
 'Apresentar relatório ao Comandante-Geral em 30 dias.',
 'Replicar o conteúdo do curso em 90 dias para oficiais da corporação.',
 'Não há obrigação específica prevista para cursos no exterior.',
 'B',
 'A obrigação de permanência após curso no exterior é idêntica à de curso nacional: período igual ao afastamento, com ressarcimento proporcional se descumprida.',
 'LC nº 194/2012, afastamento para curso',
 'dificil'),

-- ====== BLOCO 9: LC Nº 372/2026 — ALTERAÇÕES AO ESTATUTO ======

(@cat_p2,
 'A LC nº 372/2026 alterou o art. 71-A, §1º, da LC nº 194/2012. Qual mudança foi introduzida para o Soldado do Quadro de Praças Combatentes (QPC)?',
 'Promoção automática a Cabo após 3 anos de serviço.',
 'Promoção a Cabo após 5 anos, observada a antiguidade e a disponibilidade de vaga.',
 'Promoção a Cabo após 10 anos, independentemente de vaga.',
 'Promoção a 3º Sargento após 5 anos.',
 'Extinção da graduação de Soldado, com ingresso direto como Cabo.',
 'B',
 'A LC 372/2026 estabeleceu que o Soldado QPC PM/BM faz jus à promoção a Cabo ao completar 5 anos, observada a antiguidade e a disponibilidade de vaga.',
 'Art. 1º, LC nº 372/2026 (alterando art. 71-A, §1º, LC nº 194/2012)',
 'dificil'),

(@cat_p2,
 'A LC nº 372/2026 alterou o §3º do art. 22 da LC nº 194/2012 para criar/reformular o QOMed PM. Qual é a composição e o alcance máximo desse quadro?',
 'Profissionais com curso técnico em enfermagem, podendo alcançar até Tenente-Coronel.',
 'Profissionais com curso superior em Medicina, inscritos no CRM, aprovados em concurso público e promovidos a 2º Tenente após conclusão do CHO Médico, podendo alcançar até Coronel.',
 'Profissionais com qualquer formação na área de saúde, podendo alcançar até Major.',
 'Apenas cirurgiões, podendo alcançar até Coronel.',
 'Profissionais com residência médica completa, podendo alcançar até Tenente-Coronel.',
 'B',
 'O QOMed PM exige curso superior em Medicina, inscrição no CRM, concurso público, CHO Med, promoção a 2º Tenente, podendo o oficial médico alcançar até Coronel.',
 'Art. 2º, LC nº 372/2026 (alterando art. 22, §3º, LC nº 194/2012)',
 'dificil'),

(@cat_p2,
 'A LC nº 372/2026 criou o §3º-A do art. 22, instituindo o Quadro de Oficiais Dentistas (QOD PM). Qual é a exigência de formação para ingresso nesse quadro?',
 'Curso superior em Medicina com especialização em Odontologia.',
 'Curso técnico em prótese dentária reconhecido pelo MEC.',
 'Curso superior em Odontologia, reconhecido ou autorizado pelo MEC, com inscrição no Conselho Regional de Odontologia.',
 'Qualquer curso da área de saúde com ênfase em saúde bucal.',
 'Curso de Odontologia e residência obrigatória de 2 anos em cirurgia bucomaxilofacial.',
 'C',
 'O QOD PM exige curso superior em Odontologia reconhecido pelo MEC e inscrição no CRO.',
 'Art. 2º, LC nº 372/2026 (alterando art. 22, §3º-A, LC nº 194/2012)',
 'dificil'),

(@cat_p2,
 'O Quadro de Oficiais Complementares de Saúde (QOCS PM), criado pelo §3º-B do art. 22 via LC nº 372/2026, é formado por profissionais de quais áreas?',
 'Exclusivamente enfermeiros e farmacêuticos.',
 'Demais áreas de saúde (além de Medicina e Odontologia), com curso superior reconhecido pelo MEC e inscrição no Conselho Regional respectivo.',
 'Fisioterapeutas e nutricionistas exclusivamente.',
 'Profissionais de saúde com pós-graduação stricto sensu.',
 'Técnicos de saúde sem exigência de curso superior.',
 'B',
 'O QOCS PM abrange as demais áreas de saúde (além de Medicina e Odontologia), exigindo curso superior reconhecido pelo MEC e registro no conselho profissional.',
 'Art. 2º, LC nº 372/2026 (alterando art. 22, §3º-B, LC nº 194/2012)',
 'dificil'),

(@cat_p2,
 'Sobre os quadros de saúde alterados pela LC nº 372/2026, qual afirmação está INCORRETA?',
 'O oficial médico (QOMed) pode alcançar até Coronel.',
 'O oficial dentista (QOD) pode alcançar até Coronel.',
 'O oficial complementar de saúde (QOCS) ingressa a partir da conclusão do CHO Saúde.',
 'Todos os quadros de saúde exigem aprovação em concurso de provas ou de provas e títulos.',
 'O oficial dentista (QOD) pode alcançar no máximo até Tenente-Coronel.',
 'E',
 'Está incorreta porque o QOD PM pode alcançar até Coronel, conforme a LC 372/2026, e não apenas até Tenente-Coronel.',
 'LC nº 372/2026, arts. 22, §§3º, 3º-A e 3º-B, LC nº 194/2012',
 'dificil'),

-- ====== BLOCO 10: VALORES E ÉTICA MILITAR (CEDM/RR, arts. 15-22) ======

(@cat_p2,
 'O CEDM/RR define quatro manifestações essenciais do valor militar: Ética Militar, Decoro da Classe, Pundonor Militar e Compatibilidade para com o cargo. A Ética Militar é definida como:',
 'Sentimento de dignidade própria e respeito perante a comunidade.',
 'O exercício eficiente das funções e cumprimento das leis.',
 'O conjunto de regras que impõem comportamento legal e moralmente correto, destinado a incutir no militar o sentimento do dever.',
 'A observância dos preceitos morais e éticos vinculados ao cargo.',
 'A habilitação do militar ao exercício funcional.',
 'C',
 'A Ética Militar é o conjunto de regras de comportamento legal e moralmente correto que incute o sentimento do dever.',
 'Art. 19, §1º, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'O Decoro da Classe, conforme o CEDM/RR, é definido como:',
 'O exercício eficiente das funções e cumprimento das leis.',
 'A habilitação do militar ao exercício funcional.',
 'O valor moral e social da Instituição.',
 'O sentimento de dignidade do militar perante superiores.',
 'A conduta correta e ética em qualquer ocasião.',
 'C',
 'O Decoro da Classe é definido como o valor moral e social da Instituição.',
 'Art. 19, §2º, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'Qual inciso do art. 20 do CEDM/RR determina que o militar deve "zelar pelo bom nome das instituições militares estaduais e de cada um de seus integrantes, concorrendo para o bom conceito social"?',
 'Inciso I.',
 'Inciso II.',
 'Inciso V.',
 'Inciso X.',
 'Inciso XXX.',
 'A',
 'O inciso I do art. 20 estabelece o dever de zelar pelo bom nome das instituições e contribuir para o bom conceito social.',
 'Art. 20, I, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'O preceito ético do art. 20, inciso IV, do CEDM/RR, impõe ao militar qual conduta específica?',
 'Exercer a profissão com segurança e destemor.',
 'Não usar meio ilícito na produção de trabalho intelectual ou em avaliação profissional.',
 'Manter ânimo forte e fé na missão militar.',
 'Respeitar a dignidade da pessoa humana.',
 'Abster-se do uso do posto ou graduação para obter facilidades.',
 'B',
 'O inciso IV veda o uso de meio ilícito na produção de trabalho intelectual ou em avaliação profissional.',
 'Art. 20, IV, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'Qual preceito ético do CEDM/RR obriga o militar a "atuar com devotamento à comunidade, no sentido de servi-la, compreendendo os seus anseios"?',
 'Art. 20, inciso III.',
 'Art. 20, inciso VIII.',
 'Art. 20, inciso XII.',
 'Art. 20, inciso XIX.',
 'Art. 20, inciso XXV.',
 'D',
 'O inciso XIX impõe ao militar a atuação com devotamento à comunidade, no sentido de servi-la e compreender seus anseios.',
 'Art. 20, XIX, Lei nº 963/2014',
 'dificil'),

-- ====== BLOCO 11: HIERARQUIA E DISCIPLINA — DETALHES ESPECÍFICOS ======

(@cat_p2,
 'O art. 7º do CEDM/RR estabelece os círculos hierárquicos. A qual círculo pertencem o Subtenente e os Sargentos?',
 'Círculo de Oficiais Subalternos.',
 'Círculo de Praças Especiais.',
 'Círculo de Subtenentes e Sargentos.',
 'Círculo de Praças Combatentes.',
 'Círculo de Graduados.',
 'C',
 'O CEDM define o Círculo de Subtenentes e Sargentos como agrupamento hierárquico específico dessas graduações.',
 'Art. 7º, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'A disciplina militar, segundo o CEDM/RR, se manifesta essencialmente pelo(a):',
 'Obediência irrestrita a qualquer ordem recebida, sem análise de legalidade.',
 'Pronta obediência às ordens legais, utilização total das energias em prol do serviço, correção de atitudes e cooperação espontânea.',
 'Submissão absoluta ao superior hierárquico em todas as circunstâncias.',
 'Cumprimento mecânico de regulamentos sem iniciativa pessoal.',
 'Execução literal de ordens escritas exclusivamente.',
 'B',
 'A disciplina se manifesta pela obediência a ordens LEGAIS, uso total das energias, correção de atitudes e cooperação espontânea.',
 'Art. 8º, §1º, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'O CEDM/RR prevê que toda ordem deve ser cumprida sem hesitação, cabendo ao subordinado, quando a ordem for manifestamente ilegal:',
 'Cumpri-la e depois recorrer.',
 'Recusar-se a cumpri-la, representando à autoridade competente.',
 'Cumpri-la parcialmente.',
 'Solicitar que a ordem seja formalizada por escrito antes de decidir.',
 'Transferir a responsabilidade ao militar mais antigo presente.',
 'B',
 'Quando a ordem for manifestamente ilegal, o militar deve recusar-se a cumpri-la e representar à autoridade competente.',
 'Art. 9º, §§, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'No CEDM/RR, a precedência entre militares do mesmo posto ou graduação é determinada por qual critério?',
 'Pela idade biológica, em qualquer caso.',
 'Pelo número de cursos realizados.',
 'Pela antiguidade no posto ou graduação.',
 'Pelo tempo total de corporação.',
 'Pela avaliação de desempenho mais recente.',
 'C',
 'A precedência entre militares de mesmo posto/graduação é definida pela antiguidade nesse posto ou graduação.',
 'Art. 6º, §1º, Lei nº 963/2014',
 'dificil'),

-- ====== BLOCO 12: INGRESSO, POSSE E ESTÁGIO PROBATÓRIO (LC 194/2012) ======

(@cat_p2,
 'Segundo o art. 12 do Estatuto, o concurso público é composto por 4 etapas. Qual é a composição e o caráter da SEGUNDA etapa?',
 'Prova de conhecimentos, de caráter classificatório e eliminatório.',
 'Exames médicos, odontológicos, toxicológico e de aptidão física, todos de caráter eliminatório.',
 'Avaliação Psicológica, de caráter eliminatório.',
 'Investigação social, de caráter eliminatório.',
 'Exame de aptidão física isoladamente, de caráter eliminatório.',
 'B',
 'A 2ª etapa do concurso (art. 12, II) compreende os exames médicos, odontológicos, toxicológico e de aptidão física, todos de caráter eliminatório. A 3ª etapa é a Avaliação Psicológica e a 4ª é a investigação social.',
 'Art. 12, II, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'O candidato aprovado no concurso público para a PMRR/CBMRR que tiver sua classificação alterada por liminar judicial toma posse em que tipo de vaga?',
 'Vaga definitiva com todos os direitos.',
 'Vaga suplementar criada especificamente.',
 'Vaga reservada, de natureza precária.',
 'Vaga em comissão.',
 'Vaga temporária, sem estabilidade futura.',
 'C',
 'O beneficiado por liminar toma posse em vaga reservada de natureza precária, podendo ser revertida caso a decisão judicial seja reformada.',
 'Art. 16, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'O prazo para o militar nomeado tomar posse, contado da publicação do ato de nomeação, é de:',
 '15 dias, improrrogáveis.',
 '30 dias, prorrogáveis por igual período a pedido do interessado.',
 '30 dias, improrrogáveis.',
 '60 dias.',
 'O prazo fixado no edital do concurso.',
 'B',
 'O prazo de posse é de 30 dias da publicação, prorrogáveis por igual período mediante requerimento.',
 'Art. 15, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'O militar nomeado que tomar posse mas não entrar em exercício no prazo legal será:',
 'Demitido por abandono de cargo.',
 'Exonerado de ofício.',
 'Licenciado ex-officio.',
 'Transferido para a reserva não remunerada.',
 'Advertido e dado novo prazo.',
 'B',
 'A posse sem entrada em exercício no prazo legal enseja exoneração de ofício.',
 'Art. 124, parágrafo único, II, LC nº 194/2012',
 'dificil'),

-- ====== BLOCO 13: EXERCÍCIO DA FUNÇÃO E LOTAÇÃO ======

(@cat_p2,
 'Segundo o Estatuto, o militar estadual poderá ser posto à disposição de órgão federal, estadual ou municipal. Nessa hipótese, quem arca com a remuneração do militar?',
 'Sempre o órgão requisitante.',
 'Sempre a corporação de origem.',
 'O órgão requisitante, salvo se a cessão for no interesse da corporação de origem.',
 'Metade cada um.',
 'O Tesouro Estadual, independentemente do requisitante.',
 'C',
 'A regra é que o órgão requisitante assume a remuneração, exceto quando a cessão atender ao interesse da corporação de origem.',
 'Art. 36, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'O Estatuto prevê que o militar considerado como em exercício de função militar inclui aquele que está em determinadas situações. Qual das seguintes NÃO configura exercício de função militar?',
 'Instrutor ou aluno de estabelecimento de ensino no interesse da corporação.',
 'Hospitalizado por ferimento em serviço.',
 'Em gozo de licença para tratar de interesse particular.',
 'Preso preventivamente ou em cumprimento de sentença.',
 'Em trânsito por motivo de transferência.',
 'C',
 'A licença para tratar de interesse particular NÃO configura exercício de função militar; as demais situações são assim consideradas.',
 'Art. 32, §§1º e 2º, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'A agregação do militar ao respectivo quadro ocorre em quais hipóteses?',
 'Apenas quando o militar é condenado criminalmente.',
 'Quando o militar ultrapassa 2 anos de afastamento, quando é nomeado para cargo civil, quando está preso por mais de 60 dias, entre outras.',
 'Somente quando é cedido a outro órgão.',
 'Apenas durante o estágio probatório.',
 'Quando solicita transferência para a reserva.',
 'B',
 'A agregação ocorre em diversas hipóteses previstas no art. 100, incluindo nomeação para cargo não previsto no QO, aguardar transferência ex-officio, e afastamento temporário do serviço ativo.',
 'Art. 100, §1º, LC nº 194/2012',
 'dificil'),

-- ====== BLOCO 14: DIREITOS E DEVERES — DETALHES ESPECÍFICOS ======

(@cat_p2,
 'Dentre os deveres do militar estadual previstos no Estatuto, está a proibição de:',
 'Frequentar cursos de aperfeiçoamento sem autorização.',
 'Participar de gerência ou administração de sociedade ou dela ser sócio, ou exercer comércio, exceto como acionista ou quotista em sociedade anônima ou por quotas de responsabilidade limitada.',
 'Utilizar transporte público em serviço.',
 'Residir fora da sede da unidade.',
 'Solicitar passagem para a reserva antes de completar 25 anos.',
 'B',
 'O art. 40 veda comerciar ou tomar parte na administração ou gerência de sociedade, ressalvada a condição de acionista ou quotista em sociedade anônima ou por quotas de responsabilidade limitada.',
 'Art. 40, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'O Estatuto garante ao militar o direito de petição. Esse direito consiste em:',
 'Dirigir-se à imprensa para denunciar irregularidades na corporação.',
 'Requerer ou representar aos poderes públicos em defesa de direito ou interesse legítimo, individualmente ou em grupo, observada a via hierárquica.',
 'Formar sindicatos e associações para defender interesses coletivos.',
 'Apresentar queixas diretamente ao Governador sem passar pela cadeia de comando.',
 'Recorrer ao Ministério Público sem comunicação ao Comandante.',
 'B',
 'O direito de petição se exerce pela via hierárquica, individualmente ou em grupo, para requerer ou representar em defesa de direito legítimo.',
 'Art. 39, XII, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'O militar que se considerar prejudicado ou ofendido por ato de superior pode interpor queixa ou representação. O Estatuto exige qual condição fundamental para esse exercício?',
 'Que a queixa seja anônima para proteger o denunciante.',
 'Que a queixa seja apresentada por intermédio de advogado.',
 'Que a queixa seja feita por escrito, com provas ou indicação de provas, e pela via hierárquica.',
 'Que a queixa seja submetida primeiro ao Ministério Público.',
 'Que haja testemunho de pelo menos dois militares.',
 'C',
 'A queixa ou representação deve ser escrita, fundamentada com provas ou indicação de provas, e seguir a via hierárquica.',
 'Art. 39, XIII, LC nº 194/2012',
 'dificil'),

-- ====== BLOCO 15: COMPORTAMENTO E CONCEITO (CEDM/RR) ======

(@cat_p2,
 'O CEDM/RR classifica o comportamento do militar em graus. Qual alternativa apresenta a classificação correta em ordem crescente?',
 'Mau, insuficiente, regular, bom e excepcional.',
 'Péssimo, mau, regular, bom e ótimo.',
 'Insatisfatório, regular, bom, muito bom e excelente.',
 'Mau, regular, bom, muito bom e excepcional.',
 'Regular, bom, ótimo e excepcional.',
 'A',
 'O CEDM classifica o comportamento em: mau, insuficiente, regular, bom e excepcional, em ordem crescente.',
 'Art. 69, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'O militar classificado em comportamento "mau" fica sujeito a qual consequência específica?',
 'Apenas advertência administrativa.',
 'Impedimento para ser incluído no Quadro de Acesso por Merecimento e proibição de frequentar cursos.',
 'Transferência automática para a reserva.',
 'Redução de soldo em 10%.',
 'Nenhuma consequência além do registro em ficha.',
 'B',
 'O comportamento "mau" impede inclusão no QAM e proíbe a frequência a cursos de formação/aperfeiçoamento.',
 'Art. 71, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'Para ascender do comportamento "bom" para "excepcional", o militar deve permanecer sem qualquer punição por qual período mínimo?',
 '6 meses.',
 '1 ano.',
 '2 anos.',
 '3 anos.',
 '5 anos.',
 'C',
 'A progressão de comportamento "bom" para "excepcional" exige 2 anos sem qualquer nova punição.',
 'Art. 70, Lei nº 963/2014',
 'dificil'),

-- ====== BLOCO 16: VEDAÇÕES E ATIVIDADES INCOMPATÍVEIS ======

(@cat_p2,
 'O art. 21 do CEDM/RR veda ao militar da ativa, EXCETO:',
 'Exercer atividade de segurança particular.',
 'Exercer atividade comercial ou industrial.',
 'Participar de manifestação de caráter político-partidário enquanto fardado.',
 'Exercer atividade de magistério em instituição de ensino autorizada, com compatibilidade de horários.',
 'Exercer atividade sindical.',
 'D',
 'O magistério com compatibilidade de horários é exceção à vedação geral de atividades externas para o militar da ativa.',
 'Art. 21, Lei nº 963/2014 c/c Art. 40, §2º, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'O militar da ativa pode exercer atividades remuneradas fora da corporação em quais áreas, segundo a legislação em vigor?',
 'Em qualquer área, desde que autorizado pelo Comandante-Geral.',
 'Apenas em áreas de saúde ou educação, quando possuir a devida formação e houver compatibilidade de horários.',
 'Exclusivamente em empresas de segurança privada.',
 'Em atividades agropecuárias e rurais.',
 'Em nenhuma área; é vedação absoluta.',
 'B',
 'A acumulação lícita é restrita às áreas de saúde ou educação, com formação adequada e compatibilidade de horários.',
 'Art. 40, §2º, LC nº 194/2012',
 'dificil'),

-- ====== BLOCO 17: CONTAGEM DE TEMPO E COMPUTAÇÕES ======

(@cat_p2,
 'Para efeito de contagem de tempo de serviço, qual período NÃO é computado como tempo de efetivo serviço militar?',
 'Tempo de serviço prestado às Forças Armadas antes do ingresso na corporação.',
 'Tempo de afastamento por ferimento em serviço.',
 'Tempo de licença para tratar de interesse particular.',
 'Tempo de curso de formação, quando legalmente admitido.',
 'Tempo de serviço prestado nas Guardas Territoriais em atividades PM.',
 'C',
 'A licença para tratar de interesse particular não é computada como tempo de efetivo serviço.',
 'LC nº 194/2012, contagem de tempo de serviço',
 'dificil'),

(@cat_p2,
 'O Estatuto veda a superposição de tempo de serviço. O que isso significa na prática?',
 'Que o militar não pode computar tempo de serviço em dois cargos diferentes.',
 'Que um mesmo período cronológico não pode ser contado mais de uma vez para efeitos diferentes ou cumulativos.',
 'Que o tempo de serviço civil não pode ser somado ao militar.',
 'Que o tempo de serviço nas Forças Armadas não conta para a corporação estadual.',
 'Que o tempo de reserva não pode ser somado ao de ativa.',
 'B',
 'A vedação de superposição impede que o mesmo período cronológico seja contado mais de uma vez, evitando contagem duplicada.',
 'LC nº 194/2012, vedação de superposição',
 'dificil'),

(@cat_p2,
 'O tempo de serviço prestado pelo militar às Forças Armadas é averbado para qual finalidade específica?',
 'Para todos os efeitos, inclusive promoção.',
 'Apenas para efeito de aposentadoria/reserva remunerada, não para promoção.',
 'Não é averbável em hipótese alguma.',
 'Apenas para cálculo de adicional de tempo de serviço.',
 'Para promoção por antiguidade exclusivamente.',
 'B',
 'O tempo de serviço nas FA é averbado para aposentadoria/reserva, mas não conta para fins de promoção na corporação estadual.',
 'LC nº 194/2012, averbação de tempo',
 'dificil'),

-- ====== BLOCO 18: DEMISSÃO E PERDA DO CARGO ======

(@cat_p2,
 'A perda do posto e da patente do oficial somente pode ser declarada por qual órgão e em qual circunstância?',
 'Pelo Comandante-Geral, em processo administrativo disciplinar.',
 'Pelo Tribunal de Justiça, em processo judicial específico, quando o oficial for julgado indigno do oficialato ou com ele incompatível.',
 'Pelo Governador do Estado, por decreto.',
 'Pela Assembleia Legislativa, em votação por maioria qualificada.',
 'Pelo Conselho de Justificação, com trânsito em julgado.',
 'B',
 'A perda do posto e patente é competência exclusiva do Tribunal de Justiça, em processo judicial, quando o oficial for considerado indigno ou incompatível.',
 'Art. 125, §4º, CF/88 c/c LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'O Conselho de Justificação é procedimento destinado a julgar qual categoria de militar?',
 'Exclusivamente praças com mais de 10 anos de serviço.',
 'Oficiais, em todas as situações (ativa, reserva e reformado).',
 'Praças com estabilidade assegurada.',
 'Aspirantes-a-Oficial apenas.',
 'Qualquer militar, independentemente do grau.',
 'B',
 'O Conselho de Justificação é o procedimento específico para oficiais em qualquer situação funcional.',
 'LC nº 194/2012, Conselho de Justificação',
 'dificil'),

(@cat_p2,
 'O Conselho de Disciplina é destinado a julgar qual categoria de militar?',
 'Oficiais superiores.',
 'Aspirante-a-Oficial e praças com estabilidade assegurada.',
 'Todos os militares da ativa.',
 'Praças sem estabilidade apenas.',
 'Oficiais subalternos e intermediários.',
 'B',
 'O Conselho de Disciplina julga o Aspirante-a-Oficial e praças com estabilidade assegurada.',
 'LC nº 194/2012, Conselho de Disciplina',
 'dificil'),

-- ====== BLOCO 19: PRECEITOS ÉTICOS ESPECÍFICOS (art. 20 CEDM — DETALHES) ======

(@cat_p2,
 'Qual preceito ético do art. 20 do CEDM/RR veda expressamente a prática de atos que importem em discriminação de raça, credo, sexo ou origem?',
 'Inciso VI.',
 'Inciso IX.',
 'Inciso XIV.',
 'Inciso XX.',
 'Inciso XXVIII.',
 'C',
 'O inciso XIV do art. 20 veda expressamente a discriminação de raça, credo, sexo ou origem.',
 'Art. 20, XIV, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'O preceito ético que obriga o militar a "exercer a profissão com segurança e destemor" está em qual inciso do art. 20 do CEDM/RR?',
 'Inciso III.',
 'Inciso V.',
 'Inciso VII.',
 'Inciso XI.',
 'Inciso XXII.',
 'A',
 'O inciso III do art. 20 impõe o exercício da profissão militar com segurança e destemor.',
 'Art. 20, III, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'Qual preceito ético do CEDM/RR determina que o militar deve "observar os direitos e garantias fundamentais, agindo com isenção e equidade nas suas decisões"?',
 'Art. 20, inciso VI.',
 'Art. 20, inciso VIII.',
 'Art. 20, inciso X.',
 'Art. 20, inciso XVI.',
 'Art. 20, inciso XXIV.',
 'B',
 'O inciso VIII impõe observância dos direitos e garantias fundamentais com isenção e equidade.',
 'Art. 20, VIII, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'O art. 20, inciso XVIII do CEDM/RR estabelece qual preceito ético ao militar?',
 'Conduzir-se de modo não subserviente.',
 'Ter ânimo forte e fé na missão militar.',
 'Guardar sigilo sobre assuntos internos da corporação.',
 'Abster-se de fazer uso do posto, graduação ou função para obter facilidades pessoais de qualquer natureza ou para encobrir atos ilícitos próprios ou de outrem.',
 'Proceder de maneira ilibada na vida pública e particular.',
 'D',
 'O inciso XVIII veda o uso do posto, graduação ou função para obter facilidades pessoais ou encobrir atos ilícitos.',
 'Art. 20, XVIII, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'O preceito ético que impõe ao militar "ser fiel na vida militar, cumprindo os compromissos que assumiu ao ingresso na corporação, como agente público" está em qual inciso?',
 'Art. 20, inciso II.',
 'Art. 20, inciso VI.',
 'Art. 20, inciso XII.',
 'Art. 20, inciso XXVII.',
 'Art. 20, inciso XXXI.',
 'A',
 'O inciso II trata da fidelidade na vida militar e do cumprimento dos compromissos de agente público.',
 'Art. 20, II, Lei nº 963/2014',
 'dificil'),

-- ====== BLOCO 20: VIOLAÇÃO DOS DEVERES ÉTICOS E TRANSGRESSÕES ======

(@cat_p2,
 'A violação dos deveres éticos previstos no art. 20 do CEDM/RR constitui qual tipo de infração?',
 'Crime militar, processado pela Justiça Militar.',
 'Transgressão disciplinar, apurável conforme o próprio CEDM/RR.',
 'Infração administrativa civil, processada pelo Tribunal de Contas.',
 'Contravenção penal militar.',
 'Mera irregularidade sem consequências disciplinares.',
 'B',
 'A violação dos deveres éticos constitui transgressão disciplinar apurável e punível nos termos do CEDM/RR.',
 'Art. 23, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'O CEDM/RR prevê que o militar autor de transgressão disciplinar que também constitua crime poderá ser submetido, cumulativamente, a:',
 'Apenas punição disciplinar, vedada a ação penal.',
 'Apenas processo criminal, ficando prejudicada a punição disciplinar.',
 'Punição disciplinar e ação penal, pois as instâncias são independentes.',
 'Processo administrativo disciplinar ou ação penal, conforme escolha do Comandante.',
 'Arbitragem militar independente.',
 'C',
 'As instâncias disciplinar e penal são independentes; o militar pode responder em ambas.',
 'Art. 24, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'O CEDM/RR prevê que as circunstâncias agravantes da transgressão disciplinar incluem:',
 'Apenas reincidência.',
 'Reincidência, mau comportamento, prática em serviço, presença de tropa reunida, concurso de transgressores e premeditação.',
 'Somente premeditação e reincidência.',
 'Exclusivamente o mau comportamento e a prática em serviço.',
 'A antiguidade do militar no posto.',
 'B',
 'As circunstâncias agravantes são diversas e incluem reincidência, mau comportamento, prática em serviço, tropa reunida, concurso de transgressores e premeditação.',
 'Art. 29, Lei nº 963/2014',
 'dificil'),

-- ====== BLOCO 21: QUADROS E COMPOSIÇÃO — DETALHES ======

(@cat_p2,
 'Segundo o art. 22, inciso II, da LC nº 194/2012, quais são os quadros de Praças das instituições militares?',
 'Apenas o Quadro de Praças Combatentes (QPC).',
 'QPC e Quadro Especial de Praças (QEP) exclusivamente.',
 'QPC, QEP e Quadro de Praças de Saúde (QPS).',
 'Quadro de Praças Combatentes (QPC), Quadro de Praças de Saúde (QPS), Quadro Especial de Praças (QEP) e Quadro de Praças Músicos (QPM).',
 'QPC, QPS e QPM, sem Quadro Especial.',
 'D',
 'O art. 22, II, prevê quatro quadros de praças: QPC (Praças Combatentes), QPS (Praças de Saúde), QEP (Especial de Praças) e QPM (Praças Músicos).',
 'Art. 22, II, alíneas a a d, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'O Quadro Especial de Oficiais (QEO) é formado por militares oriundos de qual quadro?',
 'Do QOC exclusivamente.',
 'Do QPC, após promoção a Subtenente e conclusão de curso específico.',
 'Do QCO, após concurso interno.',
 'Dos militares oriundos do Quadro Especial de Praças (QEP PM/BM), que tenham concluído com aproveitamento o Curso de Habilitação de Oficiais.',
 'De civis com nível superior aprovados em concurso específico.',
 'D',
 'Conforme art. 22, §9º (redação LC 260/2017), o QEO é formado por militares oriundos do Quadro Especial de Praças (QEP PM/BM), que concluíram com aproveitamento o Curso de Habilitação de Oficiais.',
 'Art. 22, I, e, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'O Quadro de Oficiais Capelães (QOCap) é previsto no Estatuto. Qual é a exigência específica para ingresso nesse quadro?',
 'Ser militar da ativa há pelo menos 10 anos.',
 'Possuir curso superior na área de Teologia reconhecido pelo MEC, ser aprovado em concurso público e concluir o Curso de Habilitação para Oficial Capelão.',
 'Ser aprovado em concurso público de provas e títulos em Direito.',
 'Possuir curso superior em qualquer área e ser indicado pelo Governador.',
 'Ser oficial do QOC com vocação religiosa declarada.',
 'B',
 'Conforme art. 22, §19 (inclusão LC 260/2017), o QOCap exige curso superior em Teologia reconhecido pelo MEC, aprovação em concurso público e conclusão do Curso de Habilitação para Oficial Capelão, podendo alcançar até o posto de 2º Tenente.',
 'Art. 22, I, f, LC nº 194/2012',
 'dificil'),

-- ====== BLOCO 22: PROMOÇÃO — CRITÉRIOS DETALHADOS ======

(@cat_p2,
 'A promoção por ato de bravura decorre de qual situação específica?',
 'Cumprimento regular das metas de produtividade.',
 'Ato de excepcional coragem e valor militar praticado em operação real ou em circunstância de risco de vida.',
 'Tempo de serviço superior a 25 anos.',
 'Indicação do Comandante-Geral por mérito administrativo.',
 'Aprovação em curso de especialização com nota máxima.',
 'B',
 'A promoção por bravura decorre de ato de excepcional coragem e valor militar em operação real ou circunstância de risco de vida.',
 'Art. 83, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'A promoção por ressarcimento de preterição ocorre quando:',
 'O militar é promovido automaticamente ao completar o interstício.',
 'O militar que foi indevidamente preterido em promoção anterior tem seu direito reconhecido, sendo promovido retroativamente.',
 'O militar é promovido por decisão do Governador.',
 'O militar troca de quadro após promoção negada.',
 'O militar solicita promoção por via judicial.',
 'B',
 'O ressarcimento de preterição é a promoção retroativa do militar que comprovou ter sido indevidamente preterido.',
 'Art. 98, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'Segundo o art. 73-B, parágrafo único, da LC nº 194/2012 (incluído pela LC nº 372/2026), qual é o interstício provisório para a promoção de 1º Tenente a Capitão?',
 '12 meses.',
 '24 meses.',
 '36 meses.',
 '48 meses.',
 '60 meses.',
 'B',
 'O interstício provisório de 1º Tenente para Capitão é de 24 meses (2 anos), conforme art. 73-B, parágrafo único, incluído pela LC 372/2026.',
 'Art. 73-B, parágrafo único, LC nº 194/2012 (incluído pela LC nº 372/2026)',
 'dificil'),

(@cat_p2,
 'Qual é a condição que impede a inclusão do militar no Quadro de Acesso por Merecimento (QAM)?',
 'Estar em gozo de férias regulamentares.',
 'Estar respondendo a Conselho de Justificação ou Conselho de Disciplina.',
 'Ter sido transferido de unidade nos últimos 6 meses.',
 'Ter menos de 5 anos na corporação.',
 'Estar em exercício de atividade de ensino na corporação.',
 'B',
 'O militar respondendo a Conselho de Justificação ou Disciplina fica impedido de ser incluído no QAM.',
 'Art. 78, §1º, LC nº 194/2012',
 'dificil'),

-- ====== BLOCO 23: ELOGIOS E RECOMPENSAS — DETALHES ======

(@cat_p2,
 'O elogio coletivo, conforme o CEDM/RR, é formulado a quem e sob qual condição?',
 'A qualquer grupo de militares, sem restrição.',
 'A um grupo de militares, uma fração de tropa ou toda a organização militar que se tenha destacado por ação meritória.',
 'Apenas a pelotões que cumpriram meta operacional.',
 'Apenas quando aprovado pelo Governador.',
 'Somente a organizações militares como um todo, nunca a frações.',
 'B',
 'O elogio coletivo é formulado a grupo, fração de tropa ou OM inteira que se destacou por ação meritória.',
 'Art. 81, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'Segundo o CEDM/RR, as condecorações são classificadas em quais tipos?',
 'Apenas medalhas.',
 'Medalhas e diplomas.',
 'Ordens honoríficas, medalhas e condecorações especiais, conforme regulamentação específica.',
 'Apenas insígnias de mérito.',
 'Troféus e diplomas exclusivamente.',
 'C',
 'As condecorações incluem ordens honoríficas, medalhas e condecorações especiais, regulamentadas em normas próprias.',
 'Art. 82, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'A dispensa de serviço como recompensa pode ser total ou parcial. A dispensa total isenta o militar de:',
 'Apenas do expediente administrativo.',
 'De todos os trabalhos na OM, inclusive instruções e exercícios.',
 'Apenas de serviços extraordinários.',
 'De trabalhos de manutenção e limpeza.',
 'De serviço de escala exclusivamente.',
 'B',
 'A dispensa total isenta o militar de todos os trabalhos na OM, incluindo instruções e exercícios.',
 'Art. 80, §1º, Lei nº 963/2014',
 'dificil'),

-- ====== BLOCO 24: QUESTÕES INTERPRETATIVAS COMBINADAS ======

(@cat_p2,
 'Um militar estadual com 4 anos de efetivo serviço, classificado em comportamento "bom", solicita licença para tratar de interesse particular. Qual é a consequência, conforme a legislação?',
 'A licença é concedida sem restrição.',
 'A licença pode ser concedida, mas o período não será computado como tempo de serviço e não haverá remuneração.',
 'A licença é vedada antes de completar 10 anos.',
 'A licença é concedida com remuneração proporcional.',
 'A licença é concedida automaticamente por já ter estabilidade.',
 'B',
 'A licença pode ser concedida, porém sem remuneração e sem contagem como tempo de serviço, mesmo que o militar já tenha estabilidade (3 anos).',
 'Art. 119, LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'Um oficial realizou curso de 8 meses custeado pelo Estado e, 18 meses após o término, solicita transferência para a reserva. Qual é o procedimento correto?',
 'A transferência é concedida sem ônus.',
 'A transferência é vedada por prazo indeterminado.',
 'A transferência é concedida mediante indenização total de todas as despesas do curso.',
 'A transferência é concedida com indenização proporcional aos 6 meses faltantes.',
 'O Comandante-Geral decide discricionariamente.',
 'C',
 'Como o curso foi superior a 6 meses e a solicitação ocorre antes de 24 meses do término, a transferência exige indenização total das despesas.',
 'LC nº 194/2012, reserva remunerada após curso custeado',
 'dificil'),

(@cat_p2,
 'Um Aspirante-a-Oficial foi condenado por Tribunal Civil à pena restritiva de liberdade de 3 anos. Qual procedimento se aplica?',
 'Transferência automática para a reserva remunerada.',
 'Exclusão a bem da disciplina, por competência exclusiva do Comandante-Geral.',
 'Demissão por ato do Governador.',
 'Reforma administrativa disciplinar.',
 'Suspensão até trânsito em julgado.',
 'B',
 'Condenação à pena restritiva de liberdade superior a 2 anos enseja exclusão a bem da disciplina, cuja competência é exclusiva do Comandante-Geral.',
 'LC nº 194/2012, exclusão a bem da disciplina',
 'dificil'),

(@cat_p2,
 'Um Sargento com estabilidade foi julgado pelo Conselho de Disciplina e considerado culpado por infração grave. Qual é a consequência prevista?',
 'Apenas advertência e registro na ficha.',
 'Exclusão a bem da disciplina com perda da graduação.',
 'Transferência para a reserva com manutenção da graduação.',
 'Reforma disciplinar com remuneração proporcional.',
 'Suspensão por 60 dias.',
 'B',
 'O julgamento desfavorável pelo Conselho de Disciplina pode levar à exclusão a bem da disciplina com perda da graduação.',
 'LC nº 194/2012, exclusão a bem da disciplina',
 'dificil'),

(@cat_p2,
 'Uma praça foi empossada em cargo público de professor em universidade estadual. Qual é a providência a ser adotada pela corporação?',
 'Licenciamento ex-officio imediato.',
 'A praça pode acumular o cargo de magistério com o militar, desde que haja compatibilidade de horários.',
 'Exoneração de ofício do cargo militar.',
 'Agregação ao quadro durante o exercício do cargo civil.',
 'Transferência para a reserva remunerada de ofício.',
 'B',
 'Como o cargo é de magistério, enquadra-se na exceção de acumulação lícita prevista no Estatuto, desde que haja compatibilidade de horários.',
 'LC nº 194/2012, acumulação lícita e licenciamento',
 'dificil'),

(@cat_p2,
 'O Soldado do QPC PM completou 5 anos de serviço conforme a LC nº 372/2026. Para ser promovido a Cabo, quais condições adicionais devem ser atendidas?',
 'Apenas o decurso do tempo de 5 anos é suficiente.',
 'Deve estar no mínimo no comportamento "bom", ter antiguidade favorável e haver disponibilidade de vaga no quadro.',
 'Deve ser aprovado em exame de qualificação profissional.',
 'Deve ter completado curso de formação de Cabos.',
 'Deve ser indicado pelo Comandante de Companhia.',
 'B',
 'A LC 372/2026 exige, além dos 5 anos: comportamento mínimo "bom", antiguidade favorável e disponibilidade de vaga.',
 'Art. 71-A, §1º, LC nº 194/2012 (alterado pela LC nº 372/2026)',
 'dificil'),

(@cat_p2,
 'Um militar foi punido com 8 dias de detenção por transgressão média. Ele interpõe recurso disciplinar. Qual é o prazo para recurso e qual autoridade o julga?',
 '10 dias corridos; o próprio Comandante que puniu.',
 '5 dias úteis da publicação em BI; a autoridade imediatamente superior à que aplicou a punição.',
 '3 dias úteis; o Comandante-Geral.',
 '15 dias; o Secretário de Segurança Pública.',
 '48 horas; a autoridade que aplicou a punição.',
 'B',
 'O recurso deve ser interposto em 5 dias úteis da publicação em BI e é julgado pela autoridade imediatamente superior.',
 'Arts. 85 e 86, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'A sindicância inquisitorial concluiu pela inexistência de materialidade da transgressão. Qual providência deve ser adotada?',
 'Instaurar sindicância regular obrigatoriamente.',
 'Arquivar o procedimento, dando ciência à autoridade instauradora.',
 'Aplicar a punição mesmo sem materialidade comprovada.',
 'Encaminhar ao Conselho de Disciplina.',
 'Dar vista ao militar investigado para manifestação.',
 'B',
 'Se a sindicância inquisitorial não encontrar materialidade, o procedimento deve ser arquivado.',
 'Art. 96, I, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'Um militar reformado por invalidez permanente oriunda de acidente em serviço terá seus proventos calculados com base em:',
 'O subsídio do posto/graduação que ocupava.',
 'Proventos correspondentes ao grau hierárquico imediatamente superior ao que possuía.',
 'A média dos últimos 12 meses de remuneração.',
 'O salário mínimo nacional.',
 'Proventos proporcionais ao tempo de contribuição.',
 'B',
 'Conforme arts. 119 e 120 (redação LC 260/2017), a reforma por invalidez decorrente de acidente em serviço dá direito a proventos correspondentes ao grau hierárquico imediatamente superior.',
 'Arts. 119 e 120, LC nº 194/2012 (redação LC nº 260/2017)',
 'dificil'),

(@cat_p2,
 'O CEDM/RR prevê que o militar com comportamento classificado como "excepcional" deve ter cometido qual número máximo de transgressões leves nos últimos 5 anos?',
 'Nenhuma transgressão de qualquer natureza.',
 'Até 2 transgressões leves.',
 'Até 1 transgressão leve.',
 'O comportamento excepcional é alcançado por tempo sem punição, não por quantidade de transgressões.',
 'Até 3 transgressões leves canceladas.',
 'D',
 'O comportamento excepcional é alcançado pela progressão temporal sem punição, conforme os prazos do art. 70, não por contagem de transgressões.',
 'Art. 70, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'Qual é o prazo prescricional para a punição da transgressão disciplinar grave, segundo o CEDM/RR?',
 '2 anos.',
 '3 anos.',
 '5 anos, contados da data do fato, igual para todas as classificações.',
 '10 anos.',
 'Não há prescrição para transgressão grave.',
 'C',
 'O prazo prescricional é único de 5 anos contados da data do fato, independentemente da classificação da transgressão.',
 'Art. 35, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'No Estatuto, o oficial que tiver contra si declaração de indignidade ou incompatibilidade com o oficialato sofrerá:',
 'Demissão por ato do Comandante-Geral.',
 'Transferência compulsória para a reserva.',
 'Perda do posto e da patente, declarada por decisão do Tribunal de Justiça.',
 'Reforma administrativa disciplinar.',
 'Suspensão das funções até decisão do Governador.',
 'C',
 'A perda do posto e patente por indignidade ou incompatibilidade é declarada pelo Tribunal de Justiça.',
 'CF/88, art. 125, §4º c/c LC nº 194/2012',
 'dificil'),

(@cat_p2,
 'O art. 18 do CEDM/RR lista os valores militares. Qual alternativa apresenta CORRETAMENTE três valores expressos nesse artigo?',
 'Patriotismo, civismo e fé na missão policial/bombeiro militar.',
 'Competitividade, produtividade e rentabilidade.',
 'Imparcialidade, neutralidade e sigilo.',
 'Autonomia, independência e autossuficiência.',
 'Velocidade, precisão e discrição.',
 'A',
 'Entre os valores militares do art. 18 estão o patriotismo, o civismo e a fé na missão policial/bombeiro militar.',
 'Art. 18, Lei nº 963/2014',
 'dificil'),

(@cat_p2,
 'O preceito ético do art. 20, inciso XXVI, do CEDM/RR, veda ao militar:',
 'Criticar decisões de superiores em ambiente privado.',
 'Usar da estrutura do Estado em benefício próprio ou distribuí-la em detrimento dos fins da Administração, coibindo a transferência de tecnologia própria das funções militares para fins particulares.',
 'Participar de atividades esportivas em horário de serviço.',
 'Usar uniforme fora do horário de serviço.',
 'Frequentar estabelecimentos comerciais fardado.',
 'B',
 'O inciso XXVI veda o abuso da estrutura estatal e a transferência de tecnologia institucional para fins particulares.',
 'Art. 20, XXVI, Lei nº 963/2014',
 'dificil');

SET foreign_key_checks = 1;
